import { TeamMember } from "../types/team";

// Team member definitions
const team = {
    ZPL: new TeamMember({
        name: "ZPL",
        discord: "zapple__",
        image: "/profiles/ZPL.png",
        fc: "2877-6281-0055",
    }),
    Renverse: new TeamMember({
        name: "Renverse",
        discord: "renverse",
        image: "/profiles/Renverse.png",
    }),
    Ppeb: new TeamMember({
        name: "ppeb",
        discord: "ppeb",
        image: "/profiles/ppeb.png",
        fc: "3055-4410-4152",
    }),
    Lami: new TeamMember({
        name: "Lami",
        discord: "lamilemmy",
        image: "/profiles/lami.png",
    }),
    Gab: new TeamMember({
        name: "Gab",
        discord: "4ab",
        image: "/profiles/Gab.png",
        fc: "3484-8484-8484",
    }),
    Konekurosawa: new TeamMember({
        name: "konekurosawa",
        discord: "konekurosawa",
        image: "/profiles/konekurosawa.png",
        fc: "2877-6281-0055",
    }),
    Patchzy: new TeamMember({
        name: "patchzy",
        discord: "patchzy",
        image: "/profiles/Patchzy.png",
        fc: "0816-0438-0197",
    }),
    WantToBeeMe: new TeamMember({
        name: "WantToBeeMe",
        discord: "wanttobeeme",
        image: "/profiles/WTBM.png",
        fc: "0214-7488-7628",
    }),
    Lasagna: new TeamMember({
        name: "lasagna",
        discord: "gob.lasagna",
        image: "/profiles/lasagna.gif",
    }),
    Matellush: new TeamMember({
        name: "matellush",
        discord: "matellush",
        image: "/profiles/matellush.png",
    }),
    Noel: new TeamMember({
        name: "Noël",
        discord: "noel1908",
        image: "/profiles/noel.png",
        fc: "3316-1616-1616",
    }),
    Jonny: new TeamMember({
        name: "Jonny",
        discord: "40009",
        image: "/profiles/Jonny.png",
        fc: "0222-2222-2220",
    }),
    Roshi: new TeamMember({
        name: "Roshi",
        discord: "bcwii",
        image: "/profiles/Roshi.png",
        fc: "2277-7727-2227",
    }),
    DarkChaos: new TeamMember({
        name: "DarkChaos",
        discord: "darkchaosuk",
        image: "/profiles/DARKCHAOS.png",
        fc: "4687-5372-7718",
    }),
    QSahab: new TeamMember({
        name: "QSahab",
        discord: "qsahab",
        image: "/profiles/Qsahab.png",
        fc: "0521-3988-6931",
    }),
    Dynohack: new TeamMember({
        name: "Dynohack",
        discord: "dynohack",
        image: "/profiles/Dynohack.png",
        fc: "0001-0000-0011",
    }),
    Wrkus: new TeamMember({
        name: "wrkus",
        discord: "wrkus",
        image: "/profiles/wrkus.png",
        fc: "3006-4772-3801",
    }),
    Bodacious: new TeamMember({
        name: "bodacious",
        discord: "bodacious12",
        image: "/profiles/Bodacious.png",
        fc: "1212-1212-1245",
    }),
    Eggzact: new TeamMember({
        name: "Eggzact",
        discord: "eggzact",
        image: "/profiles/Eggzact.png",
        fc: "2243-2234-2234",
    }),
    Fen: new TeamMember({
        name: "Fen",
        discord: "fenixien",
        image: "/profiles/Fenixien.png",
        fc: "0654-0090-0000",
    }),
    Eppe: new TeamMember({
        name: "Eppe",
        discord: ".eppe.",
        image: "/profiles/Eppe.png",
        fc: "4646-6664-4446",
    }),
    Sasuke: new TeamMember({
        name: "sasuke",
        discord: "sasukeysl",
        image: "/profiles/sasuke.png",
    }),
    TheBeefBai: new TeamMember({
        name: "TheBeefBai",
        discord: "thebeefbai",
        image: "/profiles/TheBeefBai.png",
        fc: "5242-6660-9436",
    }),
    BadWolf: new TeamMember({
        name: "Bad Wolf",
        discord: ".bad.wolf",
        image: "/profiles/Bad_Wolf.png",
    }),
    Gaberboo: new TeamMember({
        name: "Gaberboo",
        discord: "gaberboo",
        image: "/profiles/Mel.png",
        fc: "2104-5339-8436",
    }),
    Zeroara: new TeamMember({
        name: "Zeraora",
        discord: "imzeraora",
        image: "/profiles/Zeraora.png",
        fc: "1165-6565-6533",
    }),
    Jacher: new TeamMember({
        name: "Jacher",
        discord: "jacher",
        image: "/profiles/jacher.png",
        fc: "4215-0712-7201",
    }),
    Y21: new TeamMember({
        name: "y21",
        discord: "y21",
        image: "/profiles/y21.png",
    }),
    Ismy: new TeamMember({
        name: "Ismy",
        discord: "ismy",
        image: "/profiles/ismy.png",
    }),
    Vabold: new TeamMember({
        name: "Vabold",
        discord: "main.dol",
        image: "/profiles/vabold.png",
    }),
    Nameless: new TeamMember({
        name: "Nameless",
        discord: "nnameless",
        image: "/profiles/nameless.png",
    }),
    THF: new TeamMember({
        name: "Toadette Hack Fan",
        discord: "toadettehackfan",
        image: "/profiles/THF.png",
        fc: "0000-0007-0426",
    }),
    Optllizer: new TeamMember({
        name: "Optllizer",
        discord: "optllizer",
        image: "/profiles/optllizer.png",
    }),
    Lotus: new TeamMember({
        name: "lotus",
        discord: "5336",
        image: "/profiles/lotus.png",
        fc: "0005-0000-0000",
    }),
    Matty: new TeamMember({
        name: "Matty",
        discord: "mattycamm",
        image: "/profiles/matty.png",
        fc: "0007-6000-6000",
    }),
    Fendi: new TeamMember({
        name: "Fendi",
        discord: "delaydrift",
        image: "/profiles/Fendi.png",
        fc: "0001-6967-0420",
    }),
    Zomb: new TeamMember({
        name: "Zomb",
        discord: "ancirian",
        image: "/profiles/zomb.png",
        fc: "4423-8166-0372",
    }),
    Empex: new TeamMember({
        name: "Empex",
        discord: "empex",
        image: "/profiles/empex.png",
        fc: "0002-0000-0002",
    }),
    Rambo: new TeamMember({
        name: "Rambo",
        discord: "rambo.glaz",
        image: "/profiles/Rambo.png",
        fc: "0000-0080-0580",
    }),
    Swim: new TeamMember({
        name: "Swim",
        discord: "swimybo",
        image: "/profiles/swim.png",
    }),
    Evy: new TeamMember({
        name: "Evy",
        discord: "evy",
        image: "/profiles/evy.png",
    }),
    Fury: new TeamMember({
        name: "Fury",
        discord: "forevrrfury",
        image: "/profiles/fury.png",
        fc: "3656-7252-3106",
    }),
    Justin: new TeamMember({
        name: "justin",
        discord: "jus2k",
        image: "/profiles/justin.png",
        fc: "3441-9984-1787",
    }),
    Karson: new TeamMember({
        name: "Karson",
        discord: "karsonwha",
        image: "/profiles/karson.png",
    }),
    PenroseCat: new TeamMember({
        name: "penrosecat",
        discord: "penrosecat",
        image: "/profiles/penrosecat.png",
        fc: "2061-5844-4775",
    }),
    Shubs: new TeamMember({
        name: "Shubs",
        discord: "shubs",
        image: "/profiles/shubs.png",
    }),
    Pattyrix: new TeamMember({
        name: "Pattyrix",
        discord: "bigpenguwin",
        image: "/profiles/pattyrix.png",
        fc: "2067-5991-2531",
    }),
    Clavey: new TeamMember({
        name: "clavey",
        discord: "claveybun",
        image: "/profiles/lumi.png",
        fc: "2325-3086-1009",
    }),
    GuiC: new TeamMember({
        name: "Gui_C__Tuga",
        discord: "gui_ctuga",
        image: "/profiles/Gui.png",
    }),
    Sep: new TeamMember({
        name: "Sep",
        discord: "ihavetheories",
        image: "/profiles/SEP.png",
        fc: "3444-1000-2882",
    }),
    Rhproof: new TeamMember({
        name: "rhproof",
        discord: "rhproof",
        image: "/profiles/rhproof.png",
    }),
    JGavidia: new TeamMember({
        name: "JGavidia",
        discord: "jgavidia",
        image: "/profiles/JG.png",
        fc: "1717-9869-8872",
    }),
    Kytr0nix: new TeamMember({
        name: "kytr0nix",
        discord: "kytr0nix",
        image: "/profiles/micha.png",
        fc: "3999-9999-9089",
    }),
    Kinsilly: new TeamMember({
        name: "Kinsilly",
        discord: "lastimosa",
        image: "/profiles/kins.png",
    }),
    Grong: new TeamMember({
        name: "grong",
        discord: "lrbeen",
        image: "/profiles/grong.png",
    }),
    MooSan: new TeamMember({
        name: "Moo-san",
        discord: "m.__.m",
        image: "/profiles/moo-san.png",
        fc: "0909-0909-9909",
    }),
    Haru: new TeamMember({
        name: "Haru00007",
        discord: "haru00007",
        image: "/profiles/haru00007.png",
    }),
    Mosgis: new TeamMember({
        name: "Mosgis",
        discord: "tkmt_aniki",
        image: "/profiles/tkmt_aniki.png"
    }),
    OrangeCake: new TeamMember({
        name: "OrangeCake_",
        discord: "notorangecake",
        image: "/profiles/OrangeCake_.png",
    }),
    Sinegia: new TeamMember({
        name: "Sinegia",
        discord: "sinseiga",
        image: "/profiles/Sinegia.png",
    }),
    StationAlpha: new TeamMember({
        name: "StationAlpha",
        discord: "stationalpha",
        image: "/profiles/StationAlpha.png",
    }),
    Seaweed: new TeamMember({
        name: "주녕",
        discord: "seaweed_jh",
        image: "/profiles/seaweed_jh.png",
    }),
    StHydrated: new TeamMember({
        name: "StHydrated",
        discord: "sthydrated",
        image: "/profiles/StHydrated.png",
    }),
    Caxap: new TeamMember({
        name: "CaXaP",
        discord: ".caxap",
        image: "/profiles/caxap.png",
    }),
    Nokiinoka: new TeamMember({
        name: "ноки",
        discord: "nokiinoka",
        image: "/profiles/nokiinoka.png",
    }),
    Yawshi: new TeamMember({
        name: "yawshi",
        discord: "yawshi__",
        image: "/profiles/yawshi.png",
        fc: "4988-1688-6126",
    }),
    Krummers: new TeamMember({
        name: "Krummers",
        discord: "krummers",
        image: "/profiles/krummers.png",
    }),
    Bubble: new TeamMember({
        name: "Bubble",
        discord: "wiioutthewindow",
        image: "/profiles/Bubble.png",
    }),
    JMM: new TeamMember({
        name: "JMM",
        discord: "jmm435",
        image: "/profiles/jmm.png",
    }),
    Yauvi: new TeamMember({
        name: "yauvi",
        discord: "yauvi",
        image: "/profiles/yauvi.gif",
    }),
    ADH: new TeamMember({
        name: "adh.",
        discord: "adh.",
        image: "/profiles/adh.png",
    }),
    JP95: new TeamMember({
        name: "jp95",
        discord: "jp95",
        image: "/profiles/jp95.png",
    }),
    XiaoyeeMoon: new TeamMember({
        name: "秋月筱翊",
        discord: "xiaoyee_moon",
        image: "/profiles/xiaoyee_moon.png",
    }),
    Chen: new TeamMember({
        name: "chen",
        discord: "yechenwei",
        image: "/profiles/yechenwei.png",
    }),
    Cod: new TeamMember({
        name: "Cod",
        discord: "cunkologist",
        image: "/profiles/cunkologist.png",
    }),
    Brazil: new TeamMember({
        name: "brazil",
        discord: "brazil",
        image: "/profiles/brazil.png",
    }),
    LuigiTime: new TeamMember({
        name: "LuigiTime202",
        discord: "luigitime202",
        image: "/profiles/luigitime202.png",
        fc: "4810-3637-9371",
    }),
}

export const teamData: Record<string, TeamMember[]> = {
    "Project Leader": [
        team.ZPL.withRole("Creator & Project Leader").withDonation("https://ko-fi.com/zpl__")
    ],
    "Team Retro WFC": [
        team.Ppeb.withRole("Retro WFC & Bot Developer, Server Administrator").withDonation("https://ko-fi.com/ppebb"),
        team.Jacher.withRole("Server Administrator & Host, Channel Developer").withDonation("https://ko-fi.com/jacherr"),
        team.Renverse.withRole("Server Co-Host").withDonation("https://streamlabs.com/renverse64/tip"),
        team.Gab.withRole("Lead Retro WFC and Discord Administrator"),
        team.Lami.withRole("Retro WFC & Bot Developer").withDonation("https://ko-fi.com/lilousky"),
    ],
    "Team WheelWizard": [
        team.Patchzy.withRole("WheelWizard Creator & Developer"),
        team.WantToBeeMe.withRole("WheelWizard Creator & Developer"),
        team.Lasagna.withRole("WheelWizard Contributor"),
        team.Matellush.withRole("WheelWizard Contributor"),
    ],
    "Website Creator": [
        team.Noel.withRole("Website Developer"),
    ],
    "Discord Community Administrators": [
        team.Gab.withRole("Lead Discord Administrator"),
        team.Jonny.withRole("Discord Administrator"),
        team.Roshi.withRole("Discord Administrator"),
        team.DarkChaos.withRole("Discord Administrator"),
        team.Ppeb.withRole("Discord Administrator"),
        team.QSahab.withRole("Discord Administrator"),
        team.Renverse.withRole("Discord Administrator"),
    ],
    "Discord Community Moderators": [
        team.Dynohack.withRole("Lead Moderator"),
        team.Wrkus.withRole("Lead Moderator"),
        team.Fen.withRole("Lead Moderator"),
        team.Jacher.withRole("Lead Moderator"),
        team.JP95.withRole("Moderator"),
        team.Cod.withRole("Moderator"),
        team.Brazil.withRole("Moderator"),
        team.LuigiTime.withRole("Moderator"),
    ],
    "RWFC Moderators": [
        team.Fen.withRole("Lead RWFC Moderator"),
        team.Jacher.withRole("Lead RWFC Moderator"),
        team.Dynohack.withRole("Lead RWFC Moderator"),
        team.Wrkus.withRole("Lead RWFC Moderator"),
        team.Eppe.withRole("RWFC Moderator"),
        team.Roshi.withRole("RWFC Moderator"),
        team.DarkChaos.withRole("RWFC Moderator"),
        team.Patchzy.withRole("RWFC Moderator"),
        team.QSahab.withRole("RWFC Moderator"),
        team.Sasuke.withRole("RWFC Moderator"),
        team.TheBeefBai.withRole("RWFC Moderator"),
        team.Ppeb.withRole("RWFC Moderator")

    ],
    Developers: [
        team.ZPL.withRole("Retro Rewind Developer"),
        team.Ppeb.withRole("Retro WFC & Bot Developer"),
        team.Gab.withRole("Tool Developer & Retro Rewind Contributor"),
        team.Jacher.withRole("Channel Developer"),
        team.Y21.withRole("Channel Developer"),
        team.Noel.withRole("Bot & Web Developer"),
        team.Dynohack.withRole("RetroReader Developer"),
    ],
    Contributors: [
        team.Rambo.withRole("Extended Teams & Other Features"),
        team.Bodacious.withRole("Nunchuck Viewer"),
        team.Zeroara.withRole("Retro Rewind Contributor"),
        team.Eppe.withRole("Language System Improvements"),
        team.Ismy.withRole("Hybrid Drift & Gecko Codes"),
        team.Gaberboo.withRole("Retro Rewind Contributor"),
        team.TheBeefBai.withRole("Retro Rewind Contributor"),
        team.Optllizer.withRole("Retro Rewind Contributor"),
        team.THF.withRole("Retro Rewind Contributor"),
        team.Konekurosawa.withRole("Server Help"),
        team.Vabold.withRole("Gecko Codes"),
        team.Nameless.withRole("Gecko Codes"),
    ],
    Translators: [
        team.Eppe.withRole("Translation Leader & French Translator"),
        team.Haru.withRole("Japanese Translator"),
        team.MooSan.withRole("Japanese Translator"),
        team.Mosgis.withRole("Japanese Translator"),
        team.Yawshi.withRole("French & Arabic Translator"),
        team.Gab.withRole("German Translator"),
        team.Kytr0nix.withRole("German Translator"),
        team.THF.withRole("German Translator"),
        team.Krummers.withRole("Dutch Translator"),
        team.Noel.withRole("Dutch Translator"),
        team.JGavidia.withRole("Spanish (EU/NTSC) Translator"),
        team.Clavey.withRole("Finnish Translator"),
        team.Ismy.withRole("Italian Translator"),
        team.Rhproof.withRole("Italian Translator"),
        team.Sep.withRole("Italian Translator"),
        team.Sinegia.withRole("Korean Translator"),
        team.StationAlpha.withRole("Korean Translator"),
        team.OrangeCake.withRole("Russian Translator"),
        team.StHydrated.withRole("Russian Translator"),
        team.Caxap.withRole("Russian Translator"),
        team.Nokiinoka.withRole("Russian Translator"),
        team.Wrkus.withRole("Turkish Translator"),
        team.Pattyrix.withRole("Czech Translator"),
        team.GuiC.withRole("Portuguese Translator"),
        team.Bubble.withRole("Portuguese Translator"),
        team.JMM.withRole("Portuguese Translator"),
        team.ADH.withRole("Arabic Translator"),
        team.Grong.withRole("Chinese (Simplified) Translator"),
        team.XiaoyeeMoon.withRole("Chinese (Simplified) Translator"),
        team.Eggzact.withRole("Hindi Translator"),
        team.Kinsilly.withRole("Norwegian Translator"),
        team.Yauvi.withRole("Croatian Translator"),
    ],
    "BKT Updaters": [
        team.Eppe.withRole("BKT Updater"),
        team.Evy.withRole("BKT Updater"),
        team.Fury.withRole("BKT Updater"),
        team.Justin.withRole("BKT Updater"),
        team.Karson.withRole("BKT Updater"),
        team.PenroseCat.withRole("BKT Updater"),
        team.Shubs.withRole("BKT Updater"),
    ],
    "Competitive Mogi Discord": [
        team.Roshi.withRole("Mogi Administrator, BDead Developer"),
        team.Jonny.withRole("Mogi Administrator"),
        team.QSahab.withRole("Mogi Administrator"),
        team.Lotus.withRole("Mogi Administrator"),
        team.Matty.withRole("Mogi Administrator"),
        team.DarkChaos.withRole("Mogi Administrator"),
        team.Dynohack.withRole("Mogi Administrator & Retro Reader Developer"),
        team.Fendi.withRole("Mogi Staff"),
        team.Eggzact.withRole("Mogi Staff"),
        team.Zomb.withRole("Mogi Staff"),
        team.Empex.withRole("Mogi Staff"),
        team.Rambo.withRole("Mogi Staff"),
        team.Swim.withRole("SwimTableBot Developer"),
        team.BadWolf.withRole("Queue Bot Developer"),
    ],
};
