// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetroRewindWebsite.Data;

#nullable disable

namespace RetroRewindWebsite.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20251230235037_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.LegacyPlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ev")
                        .HasColumnType("integer");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean");

                    b.Property<string>("MiiData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiiImageBase64")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fc");

                    b.HasIndex("IsSuspicious");

                    b.HasIndex("Pid");

                    b.HasIndex("Rank");

                    b.ToTable("LegacyPlayers");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ev")
                        .HasColumnType("integer");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiiData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiiImageBase64")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MiiImageFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SuspiciousVRJumps")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLast24Hours")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLastMonth")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLastWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Fc");

                    b.HasIndex("IsSuspicious");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Pid")
                        .IsUnique();

                    b.HasIndex("Rank");

                    b.HasIndex("VRGainLast24Hours");

                    b.HasIndex("VRGainLastMonth");

                    b.HasIndex("VRGainLastWeek");

                    b.HasIndex("MiiImageFetchedAt", "MiiData")
                        .HasFilter("\"MiiData\" IS NOT NULL AND \"MiiData\" != ''");

                    b.HasIndex("IsSuspicious", "Ev", "LastSeen");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.VRHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalVR")
                        .HasColumnType("integer");

                    b.Property<int>("VRChange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "Date");

                    b.ToTable("VRHistories");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.VRHistoryEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.PlayerEntity", "Player")
                        .WithMany("VRHistory")
                        .HasForeignKey("PlayerId")
                        .HasPrincipalKey("Pid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.PlayerEntity", b =>
                {
                    b.Navigation("VRHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
