// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetroRewindWebsite.Data;

#nullable disable

namespace RetroRewindWebsite.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20251231112209_RemoveDiscordUserId")]
    partial class RemoveDiscordUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.GhostSubmissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("CC")
                        .HasColumnType("smallint");

                    b.Property<short>("CharacterId")
                        .HasColumnType("smallint");

                    b.Property<short>("ControllerType")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("DateSet")
                        .HasColumnType("date");

                    b.Property<short>("DriftType")
                        .HasColumnType("smallint");

                    b.Property<string>("FinishTimeDisplay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FinishTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("GhostFilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Glitch")
                        .HasColumnType("boolean");

                    b.Property<short>("LapCount")
                        .HasColumnType("smallint");

                    b.Property<string>("LapSplitsMs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MiiName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Shroomless")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TTProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<short>("VehicleId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("TTProfileId");

                    b.HasIndex("TrackId");

                    b.HasIndex("TrackId", "CC");

                    b.HasIndex("TrackId", "CC", "FinishTimeMs");

                    b.ToTable("GhostSubmissions");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.LegacyPlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ev")
                        .HasColumnType("integer");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean");

                    b.Property<string>("MiiData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiiImageBase64")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fc");

                    b.HasIndex("IsSuspicious");

                    b.HasIndex("Pid");

                    b.HasIndex("Rank");

                    b.ToTable("LegacyPlayers");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ev")
                        .HasColumnType("integer");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiiData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiiImageBase64")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MiiImageFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SuspiciousVRJumps")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLast24Hours")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLastMonth")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLastWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Fc");

                    b.HasIndex("IsSuspicious");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Pid")
                        .IsUnique();

                    b.HasIndex("Rank");

                    b.HasIndex("VRGainLast24Hours");

                    b.HasIndex("VRGainLastMonth");

                    b.HasIndex("VRGainLastWeek");

                    b.HasIndex("MiiImageFetchedAt", "MiiData")
                        .HasFilter("\"MiiData\" IS NOT NULL AND \"MiiData\" != ''");

                    b.HasIndex("IsSuspicious", "Ev", "LastSeen");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TTProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentWorldRecords")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalSubmissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("TTProfiles");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TrackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("CourseId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Laps")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrackSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CourseId");

                    b.HasIndex("TrackSlot");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.VRHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalVR")
                        .HasColumnType("integer");

                    b.Property<int>("VRChange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "Date");

                    b.ToTable("VRHistories");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.GhostSubmissionEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.TTProfileEntity", "TTProfile")
                        .WithMany("GhostSubmissions")
                        .HasForeignKey("TTProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroRewindWebsite.Models.Entities.TrackEntity", "Track")
                        .WithMany("GhostSubmissions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TTProfile");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.VRHistoryEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.PlayerEntity", "Player")
                        .WithMany("VRHistory")
                        .HasForeignKey("PlayerId")
                        .HasPrincipalKey("Pid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.PlayerEntity", b =>
                {
                    b.Navigation("VRHistory");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TTProfileEntity", b =>
                {
                    b.Navigation("GhostSubmissions");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TrackEntity", b =>
                {
                    b.Navigation("GhostSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
