import type { TeamMember } from "../types/team";

export const teamData: Record<string, TeamMember[]> = {
    "Project Leader": [
        {
            name: "ZPL",
            discord: "zapple__",
            role: "Creator & Project Leader",
            donation: "https://ko-fi.com/zpl__",
            image: "/profiles/ZPL.png",
            fc: "2877-6281-0055",
        },
    ],
    "Team Retro WFC": [
        {
            name: "Renverse",
            discord: "renverse",
            role: "Host of Retro WFC Server",
            donation: "https://streamlabs.com/renverse64/tip",
            image: "/profiles/Renverse.png",
        },
        {
            name: "ppeb",
            discord: "ppeb",
            role: "Retro WFC & Bot Developer",
            donation: "https://ko-fi.com/ppebb",
            image: "/profiles/ppeb.png",
        },
        {
            name: "Lami",
            discord: "lamilemmy",
            role: "Retro WFC & Bot Developer",
            donation: "https://ko-fi.com/lilousky",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "Retro WFC Developer & Tool Developer",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "konekurosawa",
            discord: "konekurosawa",
            role: "Retro WFC Developer",
            image: "/profiles/konekurosawa.png",
            fc: "2877-6281-0055",
        },
    ],
    "Team WheelWizard": [
        {
            name: "patchzy",
            discord: "patchzy",
            role: "WheelWizard Creator & Developer",
            image: "/profiles/Patchzy.png",
            fc: "0816-0438-0197",
        },
        {
            name: "WantToBeeMe",
            discord: "wanttobeeme",
            role: "WheelWizard Creator & Developer",
            image: "/profiles/WTBM.png",
            fc: "0214-7488-7628",
        },
        {
            name: "lasagna",
            discord: "gob.lasagna",
            role: "WheelWizard Developer",
            image: "/profiles/lasagna.gif",
        },
        {
            name: "matellush",
            discord: "matellush",
            role: "Placeholder role",
            image: "/profiles/matellush.png",
        },
    ],
    "Website Creator": [
        {
            name: "Noël",
            discord: "noel1908",
            role: "Website Developer",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
    ],
    Administrators: [
        {
            name: "Jonny",
            discord: "40009",
            role: "Discord Administrator",
            image: "/profiles/Jonny.png",
            fc: "0222-2222-2220",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "Discord Administrator",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Roshi",
            discord: "bcwii",
            role: "Discord Administrator",
            image: "/profiles/Roshi.png",
            fc: "2277-7727-2227",
        },
        {
            name: "DarkChaos",
            discord: "darkchaosuk",
            role: "Discord Administrator",
            image: "/profiles/DARKCHAOS.png",
            fc: "1251-5641-0479",
        },
        {
            name: "ppeb",
            discord: "ppeb",
            role: "Discord Administrator",
            image: "/profiles/ppeb.png",
        },
        {
            name: "Qsahab",
            discord: "qsahab",
            role: "Discord Administrator",
            image: "/profiles/Qsahab.png",
            fc: "0521-3988-6931",
        },
        {
            name: "Renverse",
            discord: "renverse",
            role: "Discord Administrator",
            image: "/profiles/Renverse.png",
        },
    ],
    Moderators: [
        {
            name: "Bodacious",
            discord: "bodacious12",
            role: "Discord Moderator",
            image: "/profiles/Bodacious.png",
            fc: "1212-1212-1245",
        },
        {
            name: "Dynohack",
            discord: "dynohack",
            role: "Discord Moderator",
            image: "/profiles/Dynohack.png",
            fc: "0001-0000-0011",
        },
        {
            name: "nbats",
            discord: "nbatman",
            role: "Discord Moderator",
            image: "/profiles/nbats.png",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Discord Moderator",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
    ],
    "Community Staff": [
        {
            name: "Fendi",
            discord: "bowsercastle3",
            role: "Community Staff",
            image: "/profiles/Fendi.png",
            fc: "0001-6967-0420",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "Community Staff",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "HyperLexus",
            discord: "hyperlexus",
            role: "Community Staff",
            image: "/profiles/Lexus.png",
            fc: "0051-5000-0000",
        },
        {
            name: "Zeraora",
            discord: "imzeraora",
            role: "Community Staff",
            image: "/profiles/Zeraora.png",
            fc: "1165-6565-6533",
        },
        {
            name: "wrkus",
            discord: "wrkus",
            role: "Community Staff",
            image: "/profiles/wrkus.png",
            fc: "3006-4772-3801",
        },
    ],
    "RWFC Moderators": [
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "RWFC Moderator",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "BAMM99x",
            discord: "bamm99x",
            role: "RWFC Moderator",
            image: "/profiles/BAMM.png",
            fc: "1895-7882-2165",
        },
        {
            name: "Roshi",
            discord: "bcwii",
            role: "RWFC Moderator",
            image: "/profiles/Roshi.png",
            fc: "2277-7727-2227",
        },
        {
            name: "DarkChaos",
            discord: "darkchaosuk",
            role: "RWFC Moderator",
            image: "/profiles/DARKCHAOS.png",
            fc: "1251-5641-0479",
        },
        {
            name: "Dynohack",
            discord: "dynohack",
            role: "RWFC Moderator",
            image: "/profiles/Dynohack.png",
            fc: "0001-0000-0011",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "RWFC Moderator",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "Flavian",
            discord: "flavian01_",
            role: "RWFC Moderator",
            image: "/profiles/Flavian.png",
            fc: "1981-7080-7744",
        },
        {
            name: "Nobu",
            discord: "nobu9733",
            role: "RWFC Moderator",
            image: "/profiles/Nobu.png",
            fc: "0048-9565-4376",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "RWFC Moderator",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "patchzy",
            discord: "patchzy",
            role: "RWFC Moderator",
            image: "/profiles/Patchzy.png",
            fc: "0816-0438-0197",
        },
        {
            name: "KC",
            discord: "phiones.",
            role: "RWFC Moderator",
            image: "/profiles/KC.png",
            fc: "1809-9079-5136",
        },
        {
            name: "Qsahab",
            discord: "qsahab",
            role: "RWFC Moderator",
            image: "/profiles/Qsahab.png",
            fc: "0521-3988-6931",
        },
        {
            name: "sasuke",
            discord: "sasukeysl",
            role: "RWFC Moderator",
            image: "/profiles/sasuke.png",
        },
        {
            name: "Weebo",
            discord: "weebo64",
            role: "RWFC Moderator",
            image: "/profiles/Weebo64.png",
            fc: "4644-6466-4446",
        },
        {
            name: "wrkus",
            discord: "wrkus",
            role: "RWFC Moderator",
            image: "/profiles/wrkus.png",
            fc: "3006-4772-3801",
        },
    ],
    Developers: [
        {
            name: "Bad Wolf",
            discord: ".bad.wolf",
            role: "Developer",
            image: "/profiles/Bad_Wolf.png",
        },
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "Developer",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "Bodacious",
            discord: "bodacious12",
            role: "Mod Pack Developer",
            image: "/profiles/Bodacious.png",
            fc: "1212-1212-1245",
        },
        {
            name: "Cyrus",
            discord: "cyrustheyoshi",
            role: "Developer",
            image: "/profiles/Cyrus.png",
            fc: "1889-7856-9675",
        },
        {
            name: "Dynohack",
            discord: "dynohack",
            role: "Bot Developer",
            image: "/profiles/Dynohack.png",
            fc: "0001-0000-0011",
        },
        {
            name: "Gaberboo",
            discord: "gaberboo",
            role: "Developer",
            image: "/profiles/Mel.png",
            fc: "2104-5339-8436",
        },
        {
            name: "Zeraora",
            discord: "imzeraora",
            role: "Developer",
            image: "/profiles/Zeraora.png",
            fc: "1165-6565-6533",
        },
        {
            name: "Jacher",
            discord: "jacher",
            role: "Channel Developer",
            image: "/profiles/jacher.png",
            fc: "4215-0712-7201",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Bot & Web Developer",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "Weebo",
            discord: "weebo64",
            role: "Developer",
            image: "/profiles/Weebo64.png",
            fc: "4644-6466-4446",
        },
        {
            name: "y21",
            discord: "y21",
            role: "Developer",
            image: "/profiles/y21.png",
        },
        {
            name: "Ismy",
            discord: "ismy",
            role: "Developer",
            image: "/profiles/ismy.png",
        },
        {
            name: "Vabold",
            discord: "main.dol",
            role: "Developer",
            image: "/profiles/vabold.png",
        },
        {
            name: "Nameless",
            discord: "nnameless",
            role: "Developer",
            image: "/profiles/nameless.png",
        },
        {
            name: "Rambo",
            discord: "rambo.glaz",
            role: "Developer",
            image: "/profiles/Rambo.png",
            fc: "0000-0080-0580",
        },
    ],
    Translators: [
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "Translation Leader",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "German Translator",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Pattyrix",
            discord: "bigpenguwin",
            role: "Czech Translator",
            image: "/profiles/pattyrix.png",
        },
        {
            name: "Lumi",
            discord: "claveybun",
            role: "Translator",
            image: "/profiles/lumi.png",
            fc: "2325-3086-1009",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "Hindi Translator",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "frix",
            discord: "frixde",
            role: "Spanish Translator",
            image: "/profiles/frix.png",
            fc: "0000-0001-6722",
        },
        {
            name: "Gui_C__Tuga",
            discord: "gui_ctuga",
            role: "Translator",
            image: "/profiles/Gui.png",
        },
        {
            name: "Sep",
            discord: "ihavetheories",
            role: "Translator",
            image: "/profiles/SEP.png",
            fc: "3444-1000-2882",
        },
        {
            name: "Ismy",
            discord: "ismy",
            role: "Italian Translator",
            image: "/profiles/ismy.png",
        },
        {
            name: "JGavidia",
            discord: "jgavidia",
            role: "Spanish Translator",
            image: "/profiles/JG.png",
            fc: "1717-9869-8872",
        },
        {
            name: "kytr0nix",
            discord: "kytr0nix",
            role: "German Translator",
            image: "/profiles/micha.png",
            fc: "3999-9999-9089",
        },
        {
            name: "Kinsilly",
            discord: "lastimosa",
            role: "Translator",
            image: "/profiles/kins.png",
        },
        {
            name: "grong",
            discord: "lrbeen",
            role: "Translator",
            image: "/profiles/grong.png",
        },
        {
            name: "Moo-san",
            discord: "m..m",
            role: "Japanese Translator",
            image: "/profiles/moo-san.png",
            fc: "0909-0909-9909",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Dutch Translator",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "OrangeCake_",
            discord: "notorangecake",
            role: "Translator",
            image: "/profiles/OrangeCake_.png",
        },
        {
            name: "Sinegia",
            discord: "sinseiga",
            role: "Translator",
            image: "/profiles/Sinegia.png",
        },
        {
            name: "StationAlpha",
            discord: "stationalpha",
            role: "Translator",
            image: "/profiles/StationAlpha.png",
        },
        {
            name: "StHydrated",
            discord: "sthydrated",
            role: "Translator",
            image: "/profiles/StHydrated.png",
        },
        {
            name: "Toadette Hack Fan",
            discord: "toadettehackfan",
            role: "German Translator",
            image: "/profiles/THF.png",
            fc: "0000-0007-0426",
        },
        {
            name: "Weebo",
            discord: "weebo64",
            role: "German & Turkish Translator",
            image: "/profiles/Weebo64.png",
            fc: "4644-6466-4446",
        },
        {
            name: "wrkus",
            discord: "wrkus",
            role: "Turkish Translator",
            image: "/profiles/wrkus.png",
            fc: "3006-4772-3801",
        },
        {
            name: "yawshi",
            discord: "yawshi__",
            role: "Translator",
            image: "/profiles/yawshi.png",
            fc: "4988-1688-6126",
        },
        {
            name: "hine",
            discord: "hinepare",
            role: "🤖",
            image: "/profiles/hine.png",
            fc: "1040-0101-2006",
        },
    ],
    "Mogi Staff": [
        {
            name: "Gab",
            discord: "4ab",
            role: "Mogi Staff",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Roshi",
            discord: "bcwii",
            role: "Mogi Staff",
            image: "/profiles/Roshi.png",
            fc: "2277-7727-2227",
        },
        {
            name: "Fendi",
            discord: "bowsercastle3",
            role: "Mogi Staff",
            image: "/profiles/Fendi.png",
            fc: "0001-6967-0420",
        },
        {
            name: "DarkChaos",
            discord: "darkchaosuk",
            role: "Mogi Staff",
            image: "/profiles/DARKCHAOS.png",
            fc: "1251-5641-0479",
        },
        {
            name: "Dunx724",
            discord: "dunx724",
            role: "Mogi Staff",
            image: "/profiles/Dunx.png",
            fc: "2319-2823-4796",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "Mogi Staff",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "爽",
            discord: "ihpy",
            role: "Mogi Staff",
            image: "/profiles/ihpy.png",
        },
        {
            name: "Zap",
            discord: "lebronfan2323",
            role: "Mogi Staff",
            image: "/profiles/Zap.gif",
            fc: "0171-7995-5369",
        },
        {
            name: "Matty",
            discord: "mattycamm",
            role: "Mogi Staff",
            image: "/profiles/matty.png",
            fc: "0007-6000-6000",
        },
        {
            name: "phil",
            discord: "phil.xyz",
            role: "Mogi Staff",
            image: "/profiles/phil.png",
            fc: "0987-8432-1619",
        },
        {
            name: "stephy",
            discord: "sth3n",
            role: "Mogi Staff",
            image: "/profiles/stephy.png",
            fc: "0773-0949-9968",
        },
    ],
    "Mogi Updaters": [
        {
            name: "ka_9998",
            discord: ".9998",
            role: "Mogi Updater",
            image: "/profiles/9998.png",
            fc: "0001-0000-9998",
        },
        {
            name: "lotus",
            discord: "5336",
            role: "Mogi Updater",
            image: "/profiles/lotus.png",
            fc: "0005-0000-0000",
        },
        {
            name: "Zomb",
            discord: "ancirian",
            role: "Mogi Updater",
            image: "/profiles/zomb.png",
            fc: "4423-8166-0372",
        },
        {
            name: "Cephus",
            discord: "cephuss",
            role: "Mogi Updater",
            image: "/profiles/cephus.png",
            fc: "5111-0110-9152",
        },
        {
            name: "Izumi",
            discord: "izumimk6",
            role: "Mogi Updater",
            image: "/profiles/izumi.gif",
            fc: "0220-7770-0220",
        },
        {
            name: "kizo",
            discord: "kkizo.",
            role: "Mogi Updater",
            image: "/profiles/kizo.png",
            fc: "4859-3376-0667",
        },
        {
            name: "Cole",
            discord: "legithits",
            role: "Mogi Updater",
            image: "/profiles/Cole.png",
            fc: "0003-0050-0050",
        },
        {
            name: "Luna<3",
            discord: "mafa47",
            role: "Mogi Updater",
            image: "/profiles/mafa.png",
            fc: "1202-5913-6469",
        },
        {
            name: "vanessa",
            discord: "pastelfemme",
            role: "Mogi Updater",
            image: "/profiles/vanessa.png",
        },
        {
            name: "petemob",
            discord: "petemob",
            role: "Mogi Updater",
            image: "/profiles/petemob.png",
        },
        {
            name: "Ryan",
            discord: "ryans_",
            role: "Mogi Updater",
            image: "/profiles/ryan.png",
            fc: "0000-7770-6660",
        },
        {
            name: "sharp",
            discord: "sharpmk",
            role: "Mogi Updater",
            image: "/profiles/sharp.png",
            fc: "3699-6912-1240",
        },
        {
            name: "lakyus",
            discord: "shinatsu.",
            role: "Mogi Updater",
            image: "/profiles/lakyus.png",
            fc: "0000-0000-8335",
        },
        {
            name: "TazarLord",
            discord: "tazarlord",
            role: "Mogi Updater",
            image: "/profiles/TL.png",
            fc: "2190-4339-6355",
        },
        {
            name: "syuto",
            discord: "zsyuou",
            role: "Mogi Updater",
            image: "/profiles/syuto.png",
            fc: "1118-1111-1113",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Mogi Updater",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
    ],
};
