import type { TeamMember } from "../types/team";

export const teamData: Record<string, TeamMember[]> = {
    "Project Leader": [
        {
            name: "ZPL",
            discord: "zapple__",
            role: "Creator & Project Leader",
            donation: "https://ko-fi.com/zpl__",
            image: "/profiles/ZPL.png",
            fc: "2877-6281-0055",
        },
    ],
    "Team Retro WFC": [
        {
            name: "Renverse",
            discord: "renverse",
            role: "Host of Retro WFC Server",
            donation: "https://streamlabs.com/renverse64/tip",
            image: "/profiles/Renverse.png",
        },
        {
            name: "ppeb",
            discord: "ppeb",
            role: "Retro WFC & Bot Developer",
            donation: "https://ko-fi.com/ppebb",
            image: "/profiles/ppeb.png",
        },
        {
            name: "Lami",
            discord: "lamilemmy",
            role: "Retro WFC & Bot Developer",
            donation: "https://ko-fi.com/lilousky",
            image: "/profiles/lami.png",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "Retro WFC Developer",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "konekurosawa",
            discord: "konekurosawa",
            role: "Retro WFC Developer",
            image: "/profiles/konekurosawa.png",
            fc: "2877-6281-0055",
        },
    ],
    "Team WheelWizard": [
        {
            name: "patchzy",
            discord: "patchzy",
            role: "WheelWizard Creator & Developer",
            image: "/profiles/Patchzy.png",
            fc: "0816-0438-0197",
        },
        {
            name: "WantToBeeMe",
            discord: "wanttobeeme",
            role: "WheelWizard Creator & Developer",
            image: "/profiles/WTBM.png",
            fc: "0214-7488-7628",
        },
        {
            name: "lasagna",
            discord: "gob.lasagna",
            role: "WheelWizard Developer",
            image: "/profiles/lasagna.gif",
        },
        {
            name: "matellush",
            discord: "matellush",
            role: "WheelWizard Developer",
            image: "/profiles/matellush.png",
        },
    ],
    "Website Creator": [
        {
            name: "Noël",
            discord: "noel1908",
            role: "Website Developer",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
    ],
    Administrators: [
        {
            name: "Jonny",
            discord: "40009",
            role: "Discord Administrator",
            image: "/profiles/Jonny.png",
            fc: "0222-2222-2220",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "Discord Administrator",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Roshi",
            discord: "bcwii",
            role: "Discord Administrator",
            image: "/profiles/Roshi.png",
            fc: "2277-7727-2227",
        },
        {
            name: "DarkChaos",
            discord: "darkchaosuk",
            role: "Discord Administrator",
            image: "/profiles/DARKCHAOS.png",
            fc: "1251-5641-0479",
        },
        {
            name: "ppeb",
            discord: "ppeb",
            role: "Discord Administrator",
            image: "/profiles/ppeb.png",
        },
        {
            name: "QSahab",
            discord: "qsahab",
            role: "Discord Administrator",
            image: "/profiles/Qsahab.png",
            fc: "0521-3988-6931",
        },
        {
            name: "Renverse",
            discord: "renverse",
            role: "Discord Administrator",
            image: "/profiles/Renverse.png",
        },
    ],
    Moderators: [
        {
            name: "Dynohack",
            discord: "dynohack",
            role: "Discord Moderator",
            image: "/profiles/Dynohack.png",
            fc: "0001-0000-0011",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Discord Moderator",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "wrkus",
            discord: "wrkus",
            role: "Community Staff",
            image: "/profiles/wrkus.png",
            fc: "3006-4772-3801",
        },
    ],
    "Community Staff": [
        {
            name: "Fendi",
            discord: "delaydrift",
            role: "Community Staff",
            image: "/profiles/Fendi.png",
            fc: "0001-6967-0420",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "Community Staff",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "Fen",
            discord: "fenixien",
            role: "RWFC Moderator",
            image: "/profiles/Fenixien.png",
            fc: "0654-0090-0000",
        },
        {
            name: "HyperLexus",
            discord: "hyperlexus",
            role: "Community Staff",
            image: "/profiles/Lexus.png",
            fc: "0051-5000-0000",
        },
        {
            name: "Zeraora",
            discord: "imzeraora",
            role: "Community Staff",
            image: "/profiles/Zeraora.png",
            fc: "1165-6565-6533",
        },
    ],
    "RWFC Moderators": [
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "RWFC Moderator",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "BAMM99x",
            discord: "bamm99x",
            role: "RWFC Moderator",
            image: "/profiles/BAMM.png",
            fc: "1895-7882-2165",
        },
        {
            name: "Roshi",
            discord: "bcwii",
            role: "RWFC Moderator",
            image: "/profiles/Roshi.png",
            fc: "2277-7727-2227",
        },
        {
            name: "DarkChaos",
            discord: "darkchaosuk",
            role: "RWFC Moderator",
            image: "/profiles/DARKCHAOS.png",
            fc: "1251-5641-0479",
        },
        {
            name: "Dynohack",
            discord: "dynohack",
            role: "RWFC Moderator",
            image: "/profiles/Dynohack.png",
            fc: "0001-0000-0011",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "RWFC Moderator",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "Fen",
            discord: "fenixien",
            role: "RWFC Moderator",
            image: "/profiles/Fenixien.png",
            fc: "0654-0090-0000",
        },
        {
            name: "Flavian",
            discord: "flavian01_",
            role: "RWFC Moderator",
            image: "/profiles/Flavian.png",
            fc: "1981-7080-7744",
        },
        {
            name: "Nobu",
            discord: "nobu9733",
            role: "RWFC Moderator",
            image: "/profiles/Nobu.png",
            fc: "0048-9565-4376",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "RWFC Moderator",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "patchzy",
            discord: "patchzy",
            role: "RWFC Moderator",
            image: "/profiles/Patchzy.png",
            fc: "0816-0438-0197",
        },
        {
            name: "KC",
            discord: "phiones.",
            role: "RWFC Moderator",
            image: "/profiles/KC.png",
            fc: "1809-9079-5136",
        },
        {
            name: "QSahab",
            discord: "qsahab",
            role: "RWFC Moderator",
            image: "/profiles/Qsahab.png",
            fc: "0521-3988-6931",
        },
        {
            name: "sasuke",
            discord: "sasukeysl",
            role: "RWFC Moderator",
            image: "/profiles/sasuke.png",
        },
        {
            name: "wrkus",
            discord: "wrkus",
            role: "RWFC Moderator",
            image: "/profiles/wrkus.png",
            fc: "3006-4772-3801",
        },
        {
            name: "TheBeefBai",
            discord: "thebeefbai",
            role: "RWFC Moderator",
            image: "/profiles/TheBeefBai.png",
            fc: "5242-6660-9436",
        },
    ],
    Developers: [
        {
            name: "Bad Wolf",
            discord: ".bad.wolf",
            role: "Developer",
            image: "/profiles/Bad_Wolf.png",
        },
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "Developer",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "Tool Developer",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Bodacious",
            discord: "bodacious12",
            role: "Mod Pack Developer",
            image: "/profiles/Bodacious.png",
            fc: "1212-1212-1245",
        },
        {
            name: "Cyrus",
            discord: "cyrustheyoshi",
            role: "Developer",
            image: "/profiles/Cyrus.png",
            fc: "5069-8054-6757",
        },
        {
            name: "Dynohack",
            discord: "dynohack",
            role: "RetroReader Developer",
            image: "/profiles/Dynohack.png",
            fc: "0001-0000-0011",
        },
        {
            name: "Gaberboo",
            discord: "gaberboo",
            role: "Developer",
            image: "/profiles/Mel.png",
            fc: "2104-5339-8436",
        },
        {
            name: "Zeraora",
            discord: "imzeraora",
            role: "Developer",
            image: "/profiles/Zeraora.png",
            fc: "1165-6565-6533",
        },
        {
            name: "Jacher",
            discord: "jacher",
            role: "Channel Developer",
            image: "/profiles/jacher.png",
            fc: "4215-0712-7201",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Bot & Web Developer",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "y21",
            discord: "y21",
            role: "Developer",
            image: "/profiles/y21.png",
        },
        {
            name: "Ismy",
            discord: "ismy",
            role: "Developer",
            image: "/profiles/ismy.png",
        },
        {
            name: "Vabold",
            discord: "main.dol",
            role: "Developer",
            image: "/profiles/vabold.png",
        },
        {
            name: "Nameless",
            discord: "nnameless",
            role: "Developer",
            image: "/profiles/nameless.png",
        },
        {
            name: "Rambo",
            discord: "rambo.glaz",
            role: "Developer",
            image: "/profiles/Rambo.png",
            fc: "0000-0080-0580",
        },
        {
            name: "Toadette Hack Fan",
            discord: "toadettehackfan",
            role: "Developer",
            image: "/profiles/THF.png",
            fc: "0000-0007-0426",
        },
        {
            name: "Optllizer",
            discord: "optllizer",
            role: "Developer",
            image: "/profiles/optllizer.png",
        },
        {
            name: "TheBeefBai",
            discord: "thebeefbai",
            role: "RWFC Moderator",
            image: "/profiles/TheBeefBai.png",
            fc: "5242-6660-9436",
        },
    ],
    Translators: [
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "Translation Leader & French Translator",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "Gab",
            discord: "4ab",
            role: "German Translator",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Pattyrix",
            discord: "bigpenguwin",
            role: "Czech Translator",
            image: "/profiles/pattyrix.png",
            fc: "2067-5991-2531",
        },
        {
            name: "clavey",
            discord: "claveybun",
            role: "Finnish Translator",
            image: "/profiles/lumi.png",
            fc: "2325-3086-1009",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "Hindi Translator",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "Gui_C__Tuga",
            discord: "gui_ctuga",
            role: "Translator",
            image: "/profiles/Gui.png",
        },
        {
            name: "Sep",
            discord: "ihavetheories",
            role: "Italian Translator",
            image: "/profiles/SEP.png",
            fc: "3444-1000-2882",
        },
        {
            name: "Ismy",
            discord: "ismy",
            role: "Italian Translator",
            image: "/profiles/ismy.png",
        },
        {
            name: "JGavidia",
            discord: "jgavidia",
            role: "Spanish Translator",
            image: "/profiles/JG.png",
            fc: "1717-9869-8872",
        },
        {
            name: "kytr0nix",
            discord: "kytr0nix",
            role: "German Translator",
            image: "/profiles/micha.png",
            fc: "3999-9999-9089",
        },
        {
            name: "Kinsilly",
            discord: "lastimosa",
            role: "Translator",
            image: "/profiles/kins.png",
        },
        {
            name: "grong",
            discord: "lrbeen",
            role: "Translator",
            image: "/profiles/grong.png",
        },
        {
            name: "Moo-san",
            discord: "m..m",
            role: "Japanese Translator",
            image: "/profiles/moo-san.png",
            fc: "0909-0909-9909",
        },
        {
            name: "Noël",
            discord: "noel1908",
            role: "Dutch Translator",
            image: "/profiles/noel.png",
            fc: "3316-1616-1616",
        },
        {
            name: "OrangeCake_",
            discord: "notorangecake",
            role: "Russian Translator",
            image: "/profiles/OrangeCake_.png",
        },
        {
            name: "Sinegia",
            discord: "sinseiga",
            role: "Korean Translator",
            image: "/profiles/Sinegia.png",
        },
        {
            name: "StationAlpha",
            discord: "stationalpha",
            role: "Korean Translator",
            image: "/profiles/StationAlpha.png",
        },
        {
            name: "StHydrated",
            discord: "sthydrated",
            role: "Russian Translator",
            image: "/profiles/StHydrated.png",
        },
        {
            name: "Toadette Hack Fan",
            discord: "toadettehackfan",
            role: "German Translator",
            image: "/profiles/THF.png",
            fc: "0000-0007-0426",
        },
        {
            name: "wrkus",
            discord: "wrkus",
            role: "Turkish Translator",
            image: "/profiles/wrkus.png",
            fc: "3006-4772-3801",
        },
        {
            name: "yawshi",
            discord: "yawshi__",
            role: "French Translator",
            image: "/profiles/yawshi.png",
            fc: "4988-1688-6126",
        },
        {
            name: "hine",
            discord: "hinepare",
            role: "🤖",
            image: "/profiles/hine.png",
            fc: "1040-0101-2006",
        },
        {
            name: "Krummers",
            discord: "krummers",
            role: "Dutch Translator",
            image: "/profiles/krummers.png",
        },
        {
            name: "Bubble",
            discord: "wiioutthewindow",
            role: "Portugese Translator",
            image: "/profiles/Bubble.png",
        },
        {
            name: "yauvi",
            discord: "yauvi",
            role: "Croatian Translator",
            image: "/profiles/yauvi.gif",
        },
    ],
    "BKT Updaters": [
        {
            name: "Eppe",
            discord: ".eppe.",
            role: "BKT Updater",
            image: "/profiles/Eppe.png",
            fc: "4646-6664-4446",
        },
        {
            name: "Evy",
            discord: "evy",
            role: "BKT Updater",
            image: "/profiles/evy.png",
        },
        {
            name: "Fury",
            discord: "forevrrfury",
            role: "BKT Updater",
            image: "/profiles/fury.png",
            fc: "3656-7252-3106",
        },
        {
            name: "justin",
            discord: "jus2k",
            role: "BKT Updater",
            image: "/profiles/justin.png",
            fc: "3441-9984-1787",
        },
        {
            name: "Karson",
            discord: "karsonwha",
            role: "BKT Updater",
            image: "/profiles/karson.png",
        },
        {
            name: "penrosecat",
            discord: "penrosecat",
            role: "BKT Updater",
            image: "/profiles/penrosecat.png",
            fc: "2061-5844-4775",
        },
        {
            name: "Shubs",
            discord: "shubs",
            role: "BKT Updater",
            image: "/profiles/shubs.png",
        },
    ],
    "Mogi Staff": [
        {
            name: "Gab",
            discord: "4ab",
            role: "Mogi Staff",
            image: "/profiles/Gab.png",
            fc: "3484-8484-8484",
        },
        {
            name: "Roshi",
            discord: "bcwii",
            role: "Mogi Staff & BDead Developer",
            image: "/profiles/Roshi.png",
            fc: "2277-7727-2227",
        },
        {
            name: "Fendi",
            discord: "delaydrift",
            role: "Mogi Staff",
            image: "/profiles/Fendi.png",
            fc: "0001-6967-0420",
        },
        {
            name: "DarkChaos",
            discord: "darkchaosuk",
            role: "Mogi Staff",
            image: "/profiles/DARKCHAOS.png",
            fc: "1251-5641-0479",
        },
        {
            name: "Eggzact",
            discord: "eggzact",
            role: "Mogi Staff",
            image: "/profiles/Eggzact.png",
            fc: "2243-2234-2234",
        },
        {
            name: "Matty",
            discord: "mattycamm",
            role: "Mogi Staff",
            image: "/profiles/matty.png",
            fc: "0007-6000-6000",
        },
        {
            name: "Zomb",
            discord: "ancirian",
            role: "Mogi Staff",
            image: "/profiles/zomb.png",
            fc: "4423-8166-0372",
        },
        {
            name: "Luna<3",
            discord: "luna_47216",
            role: "Mogi Staff",
            image: "/profiles/mafa.png",
            fc: "1202-5913-6469",
        },
        {
            name: "Empex",
            discord: "empex",
            role: "Mogi Staff",
            image: "/profiles/empex.png",
            fc: "0002-0000-0002",
        },
    ],
    "Mogi Updaters": [
        {
            name: "Colemk6",
            discord: "colemk6",
            role: "Mogi Updater",
            image: "/profiles/Cole.png",
            fc: "0003-0050-0050",
        },
        {
            name: "Ftre",
            discord: "ftre7217",
            role: "Mogi Updater",
            image: "/profiles/ftre.png",
            fc: "5368-7101-7646",
        },
        {
            name: "Home",
            discord: "home9543",
            role: "Mogi Updater",
            image: "/profiles/home.png",
            fc: "4209-0681-6760",
        },
        {
            name: "Zap",
            discord: "johnnintedo",
            role: "Mogi Updater",
            image: "/profiles/Zap.gif",
            fc: "0171-7995-5369",
        },
        {
            name: "kara",
            discord: "gwuapla",
            role: "Mogi Updater",
            image: "/profiles/kara.png",
            fc: "",
        },
        {
            name: "kizo",
            discord: "kkizo.",
            role: "Mogi Updater",
            image: "/profiles/kizo.png",
            fc: "4859-3376-0667",
        },
        {
            name: "lotus",
            discord: "5336",
            role: "Mogi Updater",
            image: "/profiles/lotus.png",
            fc: "0005-0000-0000",
        },
        {
            name: "izumi",
            discord: "izumimk6",
            role: "Mogi Updater",
            image: "/profiles/izumi.gif",
            fc: "0220-7770-0220",
        },
        {
            name: "ka_9998",
            discord: ".9998",
            role: "Mogi Updater",
            image: "/profiles/9998.png",
            fc: "0001-0000-9998",
        },
        {
            name: "ticlass",
            discord: "numberart110637",
            role: "Mogi Updater",
            image: "/profiles/ticlass.png",
            fc: "",
        },
        {
            name: "phil",
            discord: "phil.xyz",
            role: "Mogi Updater",
            image: "/profiles/phil.png",
            fc: "0987-8432-1619",
        },
    ],
};
