import type { Track } from "../types/track";

export interface GroupedRetroTracks {
    [console: string]: Track[];
}

export interface TracksData {
    retro: GroupedRetroTracks;
    custom: Track[];
    battle: Track[];
}

export const tracksData: TracksData = {
    retro: {
        "SNES": [
            {
                file: 0.0,
                name: "SNES Mario Circuit 1",
                authors: "ZPL, Jasperr",
                version: "v2.7",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Mario_Circuit_1_(ZPL_%26_Jasperr)",
                youtubeUrl: "https://www.youtube.com/watch?v=N3lTIsmheSE",
            },
            {
                file: 1.0,
                name: "SNES Donut Plains 1",
                authors: "Luca",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Donut_Plains_1_(Luca)",
                youtubeUrl: "https://www.youtube.com/watch?v=8nsQOlz6QSo",
            },
            {
                file: 2.0,
                name: "SNES Ghost Valley 1",
                authors: "MilanDK",
                version: "v1.1",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Ghost_Valley_1_(MilanDK)",
                youtubeUrl: "https://youtu.be/YgtCFdsa2r0",
            },
            {
                file: 3.0,
                name: "SNES Bowser Castle 1",
                authors: "ZPL",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Bowser_Castle_1_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=ZIOSvMDtx2Y",
            },
            {
                file: 4.0,
                name: "SNES Mario Circuit 2",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Mario_Circuit_2_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=TfU6P8lsByA",
            },
            {
                file: 5.0,
                name: "SNES Choco Island 1",
                authors: "SpyKid",
                version: "v1.0",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Choco_Island_1_(SpyKid)",
                youtubeUrl: "https://www.youtube.com/watch?v=Lq6oYfCu69E",
            },
            {
                file: 6.0,
                name: "SNES Ghost Valley 2",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: "https://www.youtube.com/watch?v=ianhfCmt9WM",
            },
            {
                file: 7.0,
                name: "SNES Donut Plains 2",
                authors: "ZPL",
                version: "v2.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Donut_Plains_2_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=rk09BDuoDXw",
            },
            {
                file: 8.0,
                name: "SNES Bowser Castle 2",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Bowser_Castle_2_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=jOW7jQsQusM",
            },
            {
                file: 9.0,
                name: "SNES Mario Circuit 3",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: "https://www.youtube.com/watch?v=no5I-3DTWSQ",
            },
            {
                file: 10.0,
                name: "SNES Koopa Beach 1",
                authors: "ZPL",
                version: "v1.1",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Koopa_Beach_1_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=fpiOkRcApy0",
            },
            {
                file: 11.0,
                name: "SNES Choco Island 2",
                authors: "Slimeserver",
                version: "v3.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Choco_Island_2_(Slimeserver)",
                youtubeUrl: "https://www.youtube.com/watch?v=d8Z0ZW1FZQA",
            },
            {
                file: 12.0,
                name: "SNES Vanilla Lake 1",
                authors: "SquireTurnbolt",
                version: "v1.8",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Vanilla_Lake_1_(SquireTurnbolt)",
                youtubeUrl: "https://www.youtube.com/watch?v=h4n7emwR91g",
            },
            {
                file: 13.0,
                name: "SNES Bowser Castle 3",
                authors: "DasFragezeichen, Tock, ZPL",
                version: "v3.3-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Bowser_Castle_3_(DasFragezeichen_%26_Tock)",
                youtubeUrl: "https://www.youtube.com/watch?v=QWDYYTiEMbc",
            },
            {
                file: 14.0,
                name: "SNES Mario Circuit 4",
                authors: "ZPL",
                version: "v1.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Mario_Circuit_4_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=6nCwe9Xlesk",
            },
            {
                file: 15.0,
                name: "SNES Donut Plains 3",
                authors: "ZPL, Bear",
                version: "v2.11",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Donut_Plains_3_(Bear_%26_ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=1Rp0LTcpkQ4",
            },
            {
                file: 16.0,
                name: "SNES Koopa Beach 2",
                authors: "Luca",
                version: "v1.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Koopa_Beach_2_(Luca)",
                youtubeUrl: "https://www.youtube.com/watch?v=nX_ArmBC9zk",
            },
            {
                file: 17.0,
                name: "SNES Ghost Valley 3",
                authors: "ZPL, Omonimo747",
                version: "v1.2.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Ghost_Valley_3_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=saSqQ9GdfYU",
            },
            {
                file: 18.0,
                name: "SNES Vanilla Lake 2",
                authors: "ZPL",
                version: "v1.2",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Vanilla_Lake_2_(ZPL)",
                youtubeUrl: "https://www.youtube.com/watch?v=5LsygcT8T7w",
            },
            {
                file: 19.0,
                name: "SNES Rainbow Road",
                authors: "xBlue98",
                version: "v1.2.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Rainbow_Road_(NiAlBlack)",
                youtubeUrl: "https://www.youtube.com/watch?v=zxOJFEL77u8",
            },
            {
                file: "sfcRR",
                name: "SNES Rainbow Road U",
                authors: "ZPL, Bear",
                version: "v2.8.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Rainbow_Road_(ZPL_%26_Bear)",
                youtubeUrl: "https://www.youtube.com/watch?v=3OwqkDDSOuU",
            }
        ],
        "N64": [
            {
                file: 20.0,
                name: "N64 Luigi Raceway",
                authors: "ZPL, Skipper93653",
                version: "v2.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Luigi_Raceway_(ZPL_%26_Skipper93653)",
                youtubeUrl: null,
            },
            {
                file: 21.0,
                name: "N64 Moo Moo Farm",
                authors: "ZPL",
                version: "v1.12",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Moo_Moo_Farm_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 22.0,
                name: "N64 Koopa Troopa Beach",
                authors: "zilly",
                version: "v1.1c",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Koopa_Troopa_Beach_(zilly)",
                youtubeUrl: null,
            },
            {
                file: 23.0,
                name: "N64 Kalimari Desert",
                authors: "Sniki",
                version: "v1.0-alt2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Kalimari_Desert_(Sniki)",
                youtubeUrl: null,
            },
            {
                file: 24.0,
                name: "N64 Toad's Turnpike",
                authors: "AltairYoshi",
                version: "v2.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Toad%27s_Turnpike_(AltairYoshi)",
                youtubeUrl: null,
            },
            {
                file: 25.0,
                name: "N64 Frappe Snowland",
                authors: "AltairYoshi",
                version: "v1.41",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Frappe_Snowland_(AltairYoshi)",
                youtubeUrl: null,
            },
            {
                file: 26.0,
                name: "N64 Choco Mountain",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Choco_Mountain_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 27.0,
                name: "N64 Mario Raceway",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 28.0,
                name: "N64 Wario Stadium",
                authors: "bugsy",
                version: "v1.2",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Wario_Stadium_(bugsy)",
                youtubeUrl: null,
            },
            {
                file: 29.0,
                name: "N64 Sherbet Land",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 30.0,
                name: "N64 Royal Raceway",
                authors: "Paratroopa3",
                version: "v1.1-alt",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Royal_Raceway_(Paratroopa3)",
                youtubeUrl: null,
            },
            {
                file: 31.0,
                name: "N64 Bowser's Castle",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 32.0,
                name: "N64 DK's Jungle Parkway",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 33.0,
                name: "N64 Yoshi Valley",
                authors: "ZPL",
                version: "v1.5",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Yoshi_Valley_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 34.0,
                name: "N64 Banshee Boardwalk",
                authors: "ZPL",
                version: "v2.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Banshee_Boardwalk_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 35.0,
                name: "N64 Rainbow Road",
                authors: "cpfusion",
                version: "v1.2.1",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Rainbow_Road_(cpfusion)",
                youtubeUrl: null,
            }
        ],
        "GBA": [
            {
                file: 36.0,
                name: "GBA Peach Circuit",
                authors: "cpfusion",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Peach_Circuit_(cpfusion)",
                youtubeUrl: null,
            },
            {
                file: 37.0,
                name: "GBA Shy Guy Beach",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 38.0,
                name: "GBA Riverside Park",
                authors: "ZPL",
                version: "v1.11",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Riverside_Park_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 39.0,
                name: "GBA Bowser Castle 1",
                authors: "ZPL",
                version: "v3.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Bowser_Castle_1_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 40.0,
                name: "GBA Mario Circuit",
                authors: "ZPL",
                version: "v1.01",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Mario_Circuit_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "gMC",
                name: "GBA Mario Circuit U",
                authors: "MysterE99",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Mario_Circuit_(MysterE99)",
                youtubeUrl: null,
            },
            {
                file: 41.0,
                name: "GBA Boo Lake",
                authors: "Slimeserver",
                version: "v2.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Boo_Lake_(Slimeserver)",
                youtubeUrl: null,
            },
            {
                file: 42.0,
                name: "GBA Cheese Land",
                authors: "ChaosShadow23",
                version: "v4.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Cheese_Land_(ChaosShadow23)",
                youtubeUrl: null,
            },
            {
                file: 43.0,
                name: "GBA Bowser Castle 2",
                authors: "ZPL",
                version: "v1.1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Bowser_Castle_2_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 44.0,
                name: "GBA Luigi Circuit",
                authors: "Flint",
                version: "v2.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Luigi_Circuit_(Flint)",
                youtubeUrl: null,
            },
            {
                file: 45.0,
                name: "GBA Sky Garden",
                authors: "acaruso",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Sky_Garden_(acaruso)",
                youtubeUrl: null,
            },
            {
                file: 46.0,
                name: "GBA Cheep-Cheep Island",
                authors: "ChaosShadow23, ZPL",
                version: "v1.0-alt2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Cheep-Cheep_Island_(ChaosShadow23)",
                youtubeUrl: null,
            },
            {
                file: 47.0,
                name: "GBA Sunset Wilds",
                authors: "ZPL",
                version: "v2.0-fix",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Sunset_Wilds_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 48.0,
                name: "GBA Snow Land",
                authors: "cpfusion",
                version: "v2.1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Snow_Land_(cpfusion)",
                youtubeUrl: null,
            },
            {
                file: 49.0,
                name: "GBA Ribbon Road",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Ribbon_Road_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 50.0,
                name: "GBA Yoshi Desert",
                authors: "ZPL",
                version: "v2.0.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Yoshi_Desert_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 51.0,
                name: "GBA Bowser Castle 3",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 52.0,
                name: "GBA Lakeside Park",
                authors: "ChaosShadow23",
                version: "v3.0.rr2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Lakeside_Park_(ChaosShadow23)",
                youtubeUrl: null,
            },
            {
                file: 53.0,
                name: "GBA Broken Pier",
                authors: "ZPL",
                version: "v1.12",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Broken_Pier_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 54.0,
                name: "GBA Bowser Castle 4",
                authors: "ChaosShadow23",
                version: "v4.1-rr",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Bowser_Castle_4_(ChaosShadow23)",
                youtubeUrl: null,
            },
            {
                file: 55.0,
                name: "GBA Rainbow Road",
                authors: "ZPL",
                version: "v2.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Rainbow_Road_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "55_1",
                name: "GBA Rainbow Road DX",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Rainbow_Road_(SpyKid)",
                youtubeUrl: null,
            }
        ],
        "GCN": [
            {
                file: 56.0,
                name: "GCN Luigi Circuit",
                authors: "Tock",
                version: "v1.7",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Luigi_Circuit_(Tock)",
                youtubeUrl: null,
            },
            {
                file: 57.0,
                name: "GCN Peach Beach",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 58.0,
                name: "GCN Baby Park",
                authors: "maczkopeti",
                version: "v1.11-alt",
                laps: 7.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Baby_Park_(maczkopeti)",
                youtubeUrl: null,
            },
            {
                file: 59.0,
                name: "GCN Dry Dry Desert",
                authors: "UltraWario",
                version: "v1.0haz-pit",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Dry_Dry_Desert_(UltraWario)",
                youtubeUrl: null,
            },
            {
                file: 60.0,
                name: "GCN Mushroom Bridge",
                authors: "Tock",
                version: "v1.7",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Mushroom_Bridge_(Tock)",
                youtubeUrl: null,
            },
            {
                file: 61.0,
                name: "GCN Mario Circuit",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 62.0,
                name: "GCN Daisy Cruiser",
                authors: "Tock",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Daisy_Cruiser_(Tock)",
                youtubeUrl: null,
            },
            {
                file: 63.0,
                name: "GCN Waluigi Stadium",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 64.0,
                name: "GCN Sherbet Land",
                authors: "Tock",
                version: "v4.68",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Sherbet_Land_(Tock)",
                youtubeUrl: null,
            },
            {
                file: 65.0,
                name: "GCN Mushroom City",
                authors: "Torran",
                version: "v1.1-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Mushroom_City_(Torran)",
                youtubeUrl: null,
            },
            {
                file: 66.0,
                name: "GCN Yoshi Circuit",
                authors: "ZPL",
                version: "v2.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Yoshi_Circuit_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 67.0,
                name: "GCN DK Mountain",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 68.0,
                name: "GCN Wario Colosseum",
                authors: "MKDasher",
                version: "v1.3-alt2",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Wario_Colosseum_(MKDasher)",
                youtubeUrl: null,
            },
            {
                file: 69.0,
                name: "GCN Dino Dino Jungle",
                authors: "Tock",
                version: "v1.5.ctgp",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Dino_Dino_Jungle_(Tock)",
                youtubeUrl: null,
            },
            {
                file: 70.0,
                name: "GCN Bowser's Castle",
                authors: "ZPL",
                version: "v1.2",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Bowser%27s_Castle_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 71.0,
                name: "GCN Rainbow Road",
                authors: "ZPL",
                version: "v1.23",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Rainbow_Road_(ZPL)",
                youtubeUrl: null,
            }
        ],
        "DS": [
            {
                file: 72.0,
                name: "DS Figure 8 Circuit",
                authors: "Vanillavaquita",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Figure-8_Circuit_(Vanillavaquita)",
                youtubeUrl: null,
            },
            {
                file: 73.0,
                name: "DS Yoshi Falls",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 74.0,
                name: "DS Cheep Cheep Beach",
                authors: "ZPL, TheZoroark007, PabloMK7",
                version: "v1.1-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Cheep_Cheep_Beach_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 75.0,
                name: "DS Luigi's Mansion",
                authors: "Tock",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Luigi%27s_Mansion_(Tock)",
                youtubeUrl: null,
            },
            {
                file: 76.0,
                name: "DS Desert Hills",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 77.0,
                name: "DS Delfino Square",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 78.0,
                name: "DS Waluigi Pinball",
                authors: "Sniki",
                version: "v1.2-ctgp",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Waluigi_Pinball_(Sniki)",
                youtubeUrl: null,
            },
            {
                file: 79.0,
                name: "DS Shroom Ridge",
                authors: "ZPL",
                version: "v1.0-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Shroom_Ridge_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 80.0,
                name: "DS DK Pass",
                authors: "ZPL",
                version: "v3.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_DK_Pass_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 81.0,
                name: "DS Tick-Tock Clock",
                authors: "maczkopeti",
                version: "Beta 2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Tick-Tock_Clock_(maczkopeti)",
                youtubeUrl: null,
            },
            {
                file: 82.0,
                name: "DS Mario Circuit",
                authors: "ZPL",
                version: "v7.1-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Mario_Circuit_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 83.0,
                name: "DS Airship Fortress",
                authors: "ZPL",
                version: "v1.2-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Airship_Fortress_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 84.0,
                name: "DS Wario Stadium",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Wario_Stadium_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 85.0,
                name: "DS Peach Gardens",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 86.0,
                name: "DS Bowser Castle",
                authors: "Sniki",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Bowser_Castle_(Sniki)",
                youtubeUrl: null,
            },
            {
                file: 87.0,
                name: "DS Rainbow Road",
                authors: "ZPL",
                version: "v2.01",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Rainbow_Road_(ZPL)",
                youtubeUrl: null,
            }
        ],
        "SW": [
            {
                file: "tSR",
                name: "SW Shroom Ridge",
                authors: "SquireTurnbolt",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Shroom_Ridge_(SquireTurnbolt)",
                youtubeUrl: null,
            },
            {
                file: "sSHS",
                name: "SW Sky-High Sundae",
                authors: "ZPL",
                version: "v1.01",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SW_Sky-High_Sundae_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "sYI",
                name: "SW Yoshi's Island",
                authors: "SquireTurnbolt, TheGamingBram",
                version: "v1.31",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SW_Yoshi%27s_Island_(SquireTurnbolt_%26_TheGamingBram)",
                youtubeUrl: null,
            }
        ],
        "Wii": [
            {
                file: 88.0,
                name: "Wii Luigi Circuit",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 89.0,
                name: "Wii Moo Moo Meadows",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 90.0,
                name: "Wii Mushroom Gorge",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 91.0,
                name: "Wii Toad's Factory",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 92.0,
                name: "Wii Mario Circuit",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 93.0,
                name: "Wii Coconut Mall",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 94.0,
                name: "Wii DK Summit",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 95.0,
                name: "Wii Wario's Gold Mine",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 96.0,
                name: "Wii Daisy Circuit",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 97.0,
                name: "Wii Koopa Cape",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 98.0,
                name: "Wii Maple Treeway",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 99.0,
                name: "Wii Grumble Volcano",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 100.0,
                name: "Wii Dry Dry Ruins",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 101.0,
                name: "Wii Moonview Highway",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 102.0,
                name: "Wii Bowser's Castle",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            },
            {
                file: 103.0,
                name: "Wii Rainbow Road",
                authors: "Nintendo",
                version: "-",
                laps: "-",
                youtubeUrl: null,
            }
        ],
        "3DS": [
            {
                file: 104.0,
                name: "3DS Toad Circuit",
                authors: "Torran",
                version: "v1.4",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/MK8DX_3DS_Toad_Circuit_(3DS_Toad_Circuit_Texture)",
                youtubeUrl: null,
            },
            {
                file: 105.0,
                name: "3DS Daisy Hills",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Daisy_Hills_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 106.0,
                name: "3DS Cheep Cheep Lagoon",
                authors: "ZPL",
                version: "v2.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Cheep_Cheep_Lagoon_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 107.0,
                name: "3DS Shy Guy Bazaar",
                authors: "ZPL, Skipper93653",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Shy_Guy_Bazaar_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 108.0,
                name: "3DS Wuhu Loop",
                authors: "ZPL",
                version: "Beta",
                laps: 1.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Wuhu_Loop_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 109.0,
                name: "3DS Mario Circuit",
                authors: "ZPL, Bri",
                version: "v1.12",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Mario_Circuit_(ZPL_%26_Bri)",
                youtubeUrl: null,
            },
            {
                file: 110.0,
                name: "3DS Music Park",
                authors: "Atlas",
                version: "v2.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Music_Park_(Atlas)",
                youtubeUrl: null,
            },
            {
                file: 111.0,
                name: "3DS Rock Rock Mountain",
                authors: "ZPL",
                version: "v1.0-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Rock_Rock_Mountain_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 112.0,
                name: "3DS Piranha Plant Slide",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Piranha_Plant_Slide_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 113.0,
                name: "3DS Wario's Shipyard",
                authors: "ZPL, Skipper93653",
                version: "v2.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Wario_Shipyard_(Skipper93653)",
                youtubeUrl: null,
            },
            {
                file: 114.0,
                name: "3DS Neo Bowser City",
                authors: "ZPL",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Neo_Bowser_City_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 115.0,
                name: "3DS Maka Wuhu",
                authors: "FunkyDude15, Wexos",
                version: "Beta 3",
                laps: 1.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Maka_Wuhu_(FunkyDude15_%26_Wexos)",
                youtubeUrl: null,
            },
            {
                file: 116.0,
                name: "3DS DK Jungle",
                authors: "ZPL",
                version: "v2.12",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_DK_Jungle_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 117.0,
                name: "3DS Rosalina's Ice World",
                authors: "SquireTurnbolt",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Rosalina%27s_Ice_World_(SquireTurnbolt)",
                youtubeUrl: null,
            },
            {
                file: 118.0,
                name: "3DS Bowser's Castle",
                authors: "ZPL",
                version: "v1.2.4",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Bowser%27s_Castle_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: 119.0,
                name: "3DS Rainbow Road",
                authors: "ZPL",
                version: "v2.2-rr",
                laps: 1.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Rainbow_Road_(ZPL)",
                youtubeUrl: null,
            }
        ],
        "Wii U": [
            {
                file: "urRR",
                name: "Wii U Royal Raceway",
                authors: "ZPL",
                version: "v1.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Royal_Raceway_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uCL",
                name: "Wii U Cheese Land",
                authors: "ZPL",
                version: "v3.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Cheese_Land_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "urRiR",
                name: "Wii U Ribbon Road",
                authors: "Gabriela_",
                version: "v2.5r",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Ribbon_Road_(Gabriela_)",
                youtubeUrl: null,
            },
            {
                file: "uBP",
                name: "Wii U Baby Park",
                authors: "ZPL, SamanthaMK",
                version: "v1.1",
                laps: 7.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Baby_Park_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "urDDD",
                name: "Wii U Dry Dry Desert",
                authors: "ZPL",
                version: "v1.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Dry_Dry_Desert_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uSL",
                name: "Wii U Sherbet Land",
                authors: "ZPL, Brawlboxgaming",
                version: "v1.21-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Sherbet_Land_(Brawlboxgaming_%26_ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uTTC",
                name: "Wii U Tick-Tock Clock",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Tick-Tock_Clock_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uMKS",
                name: "Wii U Mario Kart Stadium",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Mario_Kart_Stadium_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uSSC",
                name: "Wii U Sweet Sweet Canyon",
                authors: "Cats4Life",
                version: "v1.12",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Sweet_Sweet_Canyon_(Cats4Life)",
                youtubeUrl: null,
            },
            {
                file: "uTR",
                name: "Wii U Thwomp Ruins",
                authors: "SquireTurnbolt",
                version: "v1.8",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Thwomp_Ruins_(SquireTurnbolt)",
                youtubeUrl: null,
            },
            {
                file: "uMC",
                name: "Wii U Mario Circuit",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Mario_Circuit_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uTH",
                name: "Wii U Toad Harbor",
                authors: "ZPL",
                version: "v1.01",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Toad_Harbor_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uTM",
                name: "Wii U Twisted Mansion",
                authors: "TheGamingBram",
                version: "v2.7-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Twisted_Mansion_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "uSGF",
                name: "Wii U Shy Guy Falls",
                authors: "SamanthaMK",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Shy_Guy_Falls_(SamanthaMK)",
                youtubeUrl: null,
            },
            {
                file: "uDS",
                name: "Wii U Dolphin Shoals",
                authors: "MrFluffy",
                version: "v1.1.rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Dolphin_Shoals_(MrFluffy)",
                youtubeUrl: null,
            },
            {
                file: "uE",
                name: "Wii U Electrodrome",
                authors: "SquireTurnbolt",
                version: "v1.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Electrodrome_(SquireTurnbolt)",
                youtubeUrl: null,
            },
            {
                file: "uMW",
                name: "Wii U Mount Wario",
                authors: "TheGamingBram, Cats4Life",
                version: "v1.0",
                laps: 1.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Mount_Wario_(TheGamingBram_%26_Cats4Life)",
                youtubeUrl: null,
            },
            {
                file: "uCC",
                name: "Wii U Cloudtop Cruise",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Cloudtop_Cruise_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uBDD",
                name: "Wii U Bone-Dry Dunes",
                authors: "Luca",
                version: "Beta 3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Bone-Dry_Dunes_(Luca)",
                youtubeUrl: null,
            },
            {
                file: "uBC",
                name: "Wii U Bowser's Castle",
                authors: "TheGamingBram, Cats4Life",
                version: "v4.11-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Bowser%27s_Castle_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "uRR",
                name: "Wii U Rainbow Road",
                authors: "Squadaloo",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Rainbow_Road_(Squadaloo)",
                youtubeUrl: null,
            },
            {
                file: "uMuC",
                name: "Wii U Mute City",
                authors: "Cal",
                version: "v1.15",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Mute_City_(Cal)",
                youtubeUrl: null,
            },
            {
                file: "uEA",
                name: "Wii U Excitebike Arena",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Excitebike_Arena_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uHC",
                name: "Wii U Hyrule Circuit",
                authors: "Ermelber, ZPL",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Hyrule_Circuit_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uWW",
                name: "Wii U Wild Woods",
                authors: "TheGamingBram",
                version: "v2.2-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Wild_Woods_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "uAC",
                name: "Wii U Animal Crossing",
                authors: "ZPL",
                version: "v1.0-summer-rr2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Animal_Crossing_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "uSS",
                name: "Wii U Super Bell Subway",
                authors: "TheGamingBram",
                version: "v2.5-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Super_Bell_Subway_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "uBB",
                name: "Wii U Big Blue",
                authors: "ZPL",
                version: "v1.01",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Big_Blue_(ZPL)",
                youtubeUrl: null,
            }
        ],
        "Tour": [
            {
                file: "trBC3",
                name: "Tour Bowser Castle 3",
                authors: "ZPL",
                version: "v2.11",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Bowser_Castle_3_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "trCM",
                name: "Tour Choco Mountain",
                authors: "TacoJosh",
                version: "v1.11",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/N64_Choco_Mountain_(TacoJosh)",
                youtubeUrl: null,
            },
            {
                file: "trPC",
                name: "Tour Peach Circuit",
                authors: "Funky Racer",
                version: "v1.51",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Peach_Circuit_(FunkyRacer)",
                youtubeUrl: null,
            },
            {
                file: "trRP",
                name: "Tour Riverside Park",
                authors: "ZPL",
                version: "v2.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Riverside_Park_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "trBL",
                name: "Tour Boo Lake",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Boo_Lake_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "trSG",
                name: "Tour Sky Garden",
                authors: "Luca",
                version: "v1.0.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Sky_Garden_(Luca)",
                youtubeUrl: null,
            },
            {
                file: "trCCI",
                name: "Tour Cheep-Cheep Island",
                authors: "SquireTurnbolt, Kozakura",
                version: "v1.0-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Cheep-Cheep_Island_(SquireTurnbolt_%26_Kozakura)",
                youtubeUrl: null,
            },
            {
                file: "trSW",
                name: "Tour Sunset Wilds",
                authors: "Luca",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Sunset_Wilds_(Luca)",
                youtubeUrl: null,
            },
            {
                file: "trSL",
                name: "Tour Snow Land",
                authors: "ZPL",
                version: "v2.3",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Snow_Land_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "trLP",
                name: "Tour Lakeside Park",
                authors: "ZPL, CyrusTheYoshi",
                version: "v3.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Lakeside_Park_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "tDKS",
                name: "Tour DK Summit",
                authors: "SquireTurnbolt",
                version: "v1.1-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_DK_Summit_(SquireTurnbolt)",
                youtubeUrl: null,
            },
            {
                file: "tTB",
                name: "Tour Tokyo Blur",
                authors: "SamanthaMK",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Tokyo_Blur_2_(SamanthaMK)",
                youtubeUrl: null,
            },
            {
                file: "tVV",
                name: "Tour Vancouver Velocity",
                authors: "ZPL, Eider",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Vancouver_Velocity_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "tSingS",
                name: "Tour Singapore Speedway",
                authors: "FunkyRacer",
                version: "v2.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Singapore_Speedway_2_(FunkyRacer)",
                youtubeUrl: null,
            },
            {
                file: "tMD",
                name: "Tour Madrid Drive",
                authors: "FunkyRacer",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Madrid_Drive_2_(FunkyRacer)",
                youtubeUrl: null,
            },
            {
                file: "tMM",
                name: "Tour Merry Mountain",
                authors: "Luca, AltairYoshi",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Merry_Mountain_(Luca_%26_AltairYoshi)",
                youtubeUrl: null,
            },
            {
                file: "tNH",
                name: "Tour Ninja Hideaway",
                authors: "TheGamingBram",
                version: "v2.81",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Ninja_Hideaway_(TheGamingBram)",
                youtubeUrl: null,
            }
        ],
        "RMX": [
            {
                file: "rMC1",
                name: "RMX Mario Circuit 1",
                authors: "ZPL",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Mario_Circuit_1_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "rCI1",
                name: "RMX Choco Island 1",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Choco_Island_1_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "rRR1",
                name: "RMX Rainbow Road 1",
                authors: "Luca, Kozakura",
                version: "v1.2-rr",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Rainbow_Road_1_(Luca_%26_Kozakura)",
                youtubeUrl: null,
            },
            {
                file: "rRR2",
                name: "RMX Rainbow Road 2",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Rainbow_Road_2_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "rVL1",
                name: "RMX Vanilla Lake 1",
                authors: "Cal",
                version: "v1.01-wtp",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Vanilla_Lake_1_(Cal)",
                youtubeUrl: null,
            },
            {
                file: "rVL2",
                name: "RMX Vanilla Lake 2",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Vanilla_Lake_2_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "rGV1",
                name: "RMX Ghost Valley 1",
                authors: "Kozakura",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Ghost_Valley_1_(Kozakura)",
                youtubeUrl: null,
            },
            {
                file: "rBC1",
                name: "RMX Bowser Castle 1",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Bowser%27s_Castle_1_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "rDP1",
                name: "RMX Donut Plains 1",
                authors: "Luca",
                version: "v1.2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/RMX_Donut_Plains_1_(Luca)",
                youtubeUrl: null,
            }
        ],
        "GP": [
            {
                file: "gpMB",
                name: "GP Mario Beach",
                authors: "SuperMario64DS, DJ Lowgey",
                version: "v2.0 Alpha 1 Hotfix 2",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Mario_Beach_(SuperMario64DS_%26_DJ_Lowgey)",
                youtubeUrl: null,
            },
            {
                file: "gpMH",
                name: "GP Mario Highway",
                authors: "ZPL",
                version: "v1.0",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Mario_Highway_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "gpBR",
                name: "GP Bananan Ruins",
                authors: "Dylanmario",
                version: "v1.0.mkd",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Bananan_Ruins_(Dylanmario)",
                youtubeUrl: null,
            },
            {
                file: "gpSP",
                name: "GP Snow Panic",
                authors: "Dylanmario",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Snow_Panic_(Dylanmario)",
                youtubeUrl: null,
            },
            {
                file: "gpBC",
                name: "GP Bowser's Castle",
                authors: "TheGamingBram",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Bowser%27s_Castle_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "gpCW",
                name: "GP Castle Wall",
                authors: "TheGamingBram",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Castle_Wall_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "gpRC",
                name: "GP Rainbow Coaster",
                authors: "Diego Vapy",
                version: "v1.2",
                laps: 2.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/GP_Rainbow_Coaster_(Diego_Vapy)",
                youtubeUrl: null,
            }
        ],
        "SW2": [
            {
                file: "sw2MBC",
                name: "SW2 Mario Bros. Circuit",
                authors: "TheGamingBram",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SW2_Mario_Bros._Circuit_(TheGamingBram)",
                youtubeUrl: null,
            },
            {
                file: "sw2WS",
                name: "SW2 Whistlestop Summit",
                authors: "Outlaw Runner",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SW2_Whistlestop_Summit_(Outlaw_Runner)",
                youtubeUrl: null,
            },
            {
                file: "sw2CCF",
                name: "SW2 Cheep Cheep Falls",
                authors: "TheGamingBram, Cats4Life",
                version: "v1.1",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/SW2_Cheep_Cheep_Falls_(TheGamingBram_%26_Cats4Life)",
                youtubeUrl: null,
            }
        ],
        "Beta": [
            {
                file: "sfcDP1",
                name: "Beta Donut Plains 1",
                authors: "ZPL",
                version: "v1.1",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Donut_Plains_1_Beta_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "sfcDP2",
                name: "Beta Donut Plains 2",
                authors: "ZPL",
                version: "v1.02",
                laps: 5.0,
                wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Donut_Plains_2_Beta_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "dsDS",
                name: "Beta Delfino Square",
                authors: "ZPL",
                version: "v1.13",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Delfino_Square_Kiosk_(ZPL)",
                youtubeUrl: null,
            },
            {
                file: "wDDR",
                name: "Beta Dry Dry Ruins",
                authors: "Cats4Life",
                version: "v1.01",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Wii_Dry_Dry_Ruins_Beta",
                youtubeUrl: null,
            },
            {
                file: "dsDC",
                name: "Beta Dokan Course",
                authors: "Wingcapman, Luke Chandler",
                version: "v1.04",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/Warp_Pipe_Island",
                youtubeUrl: null,
            },
            {
                file: "dsNB",
                name: "Beta Nokonoko Beach",
                authors: "ZPL",
                version: "v1.0",
                laps: "-",
                wikiUrl: "https://wiki.tockdom.com/wiki/DS_Nokonoko_Beach_(ZPL)",
                youtubeUrl: null,
            }
        ],
    },
    custom: [
        {
            file: "Z0",
            name: "Phendrana Frostbite",
            authors: "Fuffina, ISwearChris",
            version: "v2.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Phendrana_Frostbite",
            youtubeUrl: null,
        },
        {
            file: "Z1",
            name: "Honeymoon Lune",
            authors: "SquireTurnbolt",
            version: "v2.1.scp",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Honeymoon_Lune",
            youtubeUrl: null,
        },
        {
            file: "Z2",
            name: "Pok\u00e9 Floats",
            authors: "G-Force",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Pok%C3%A9_Floats_(G-Force)",
            youtubeUrl: null,
        },
        {
            file: "Z3",
            name: "DK Jungle Tour",
            authors: "zatchi",
            version: "v1.3",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/DK_Jungle_Tour_(zatchi)",
            youtubeUrl: null,
        },
        {
            file: "Z4",
            name: "Terra Ursae",
            authors: "Bear",
            version: "v1.2.2b",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Terra_Ursae",
            youtubeUrl: null,
        },
        {
            file: "Z5",
            name: "Confectionery Cliffs",
            authors: "Bear, ZPL",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Confectionery_Cliffs",
            youtubeUrl: null,
        },
        {
            file: "Z6",
            name: "WP Tanks!",
            authors: "Brawlboxgaming",
            version: "v3.0.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/WP_Tanks!",
            youtubeUrl: null,
        },
        {
            file: "Z7",
            name: "Cloud Mist Castle",
            authors: "BroOfFun",
            version: "v1.0.mkd",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Cloud_Mist_Castle",
            youtubeUrl: null,
        },
        {
            file: "Z8",
            name: "Rooster Island",
            authors: "BroOfFun",
            version: "v1.0-beta3",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Rooster_Island_(BroOFun)",
            youtubeUrl: null,
        },
        {
            file: "Z9",
            name: "Wario's Cosmic Construction",
            authors: "AltairYoshi, JadenMKW",
            version: "v1.4",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Wario%27s_Cosmic_Construction",
            youtubeUrl: null,
        },
        {
            file: "Z10",
            name: "Jiyuu Village",
            authors: "Jiyuu",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Jiyuu_Village",
            youtubeUrl: null,
        },
        {
            file: "Z11",
            name: "Cargo Bay",
            authors: "Shorky, Cal, KC",
            version: "v1.1",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Cargo_Bae_(Cargo_Bay_Texture)",
            youtubeUrl: null,
        },
        {
            file: "Z12",
            name: "Jigsaw Circuit",
            authors: "Cal",
            version: "v1.21",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Jigsaw_Circuit",
            youtubeUrl: null,
        },
        {
            file: "Z13",
            name: "Cruel Angel's Thesis",
            authors: "Cal",
            version: "v2.0.ctgp",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Cruel_Angel%27s_Thesis",
            youtubeUrl: null,
        },
        {
            file: "Z14",
            name: "Whispy Woodlands",
            authors: "Bear, ISwearChris, Kit",
            version: "Beta",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Whispy_Woodlands",
            youtubeUrl: null,
        },
        {
            file: "Z15",
            name: "Stargaze Summit",
            authors: "Ferv",
            version: "v1.2b",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Stargaze_Summit",
            youtubeUrl: null,
        },
        {
            file: "Z16",
            name: "Good Egg Drive",
            authors: "Wraith Hopper",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Good_Egg_Drive",
            youtubeUrl: null,
        },
        {
            file: "Z17",
            name: "Starry Cityscape",
            authors: "bugsy",
            version: "v1.1-Hotfix",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Starry_Cityscape",
            youtubeUrl: null,
        },
        {
            file: "Z18",
            name: "Stickerbush Sunset",
            authors: "Fuffina",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Stickerbush_Sunset_(Stickerbush_Serenity_Texture)",
            youtubeUrl: null,
        },
        {
            file: "Z19",
            name: "Alone and Incomplete",
            authors: "ISwearChris",
            version: "v1.7",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Alone_and_Incomplete_(The_Journey_to_Fix_a_Broken_Heart)",
            youtubeUrl: null,
        },
        {
            file: "Z20",
            name: "Gallant Grotto",
            authors: "ISwearChris",
            version: "v1.31-CTGP",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Gallant_Grotto",
            youtubeUrl: null,
        },
        {
            file: "Z21",
            name: "Fort Francis",
            authors: "JadenMKW",
            version: "v3.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Fort_Francis",
            youtubeUrl: null,
        },
        {
            file: "Z22",
            name: "Bowser Jr.'s Fort",
            authors: "MrFluffy",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Bowser_Jr.%27s_Fort_(MrFluffy)",
            youtubeUrl: null,
        },
        {
            file: "Z23",
            name: "Backside of the TV",
            authors: "GioMacGrillin",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Backside_of_the_TV",
            youtubeUrl: null,
        },
        {
            file: "Z24",
            name: "Garden of Dreams",
            authors: "Jiyuu",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Garden_of_Dreams",
            youtubeUrl: null,
        },
        {
            file: "Z25",
            name: "Overgrown Temple",
            authors: "JoeyMK",
            version: "v1.21",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Overgrown_Temple",
            youtubeUrl: null,
        },
        {
            file: "Z26",
            name: "Lava Lake",
            authors: "JorisMKW",
            version: "v2.3.mkd",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Lava_Lake",
            youtubeUrl: null,
        },
        {
            file: "Z27",
            name: "Timber Rapids",
            authors: "ZPL, Kozakura",
            version: "Beta",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Timber_Rapids",
            youtubeUrl: null,
        },
        {
            file: "Z28",
            name: "Musical Cliff",
            authors: "Luca",
            version: "v1.3",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Musical_Cliff",
            youtubeUrl: null,
        },
        {
            file: "Z29",
            name: "Toad's Temple",
            authors: "LucioWins, tarsa129",
            version: "v2.0",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Toad%27s_Temple",
            youtubeUrl: null,
        },
        {
            file: "Z30",
            name: "Luncheon Tour",
            authors: "Luke Chandler",
            version: "v1.16.mkd",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Luncheon_Tour",
            youtubeUrl: null,
        },
        {
            file: "Z31",
            name: "Shy Guy Lumber Co.",
            authors: "Metabus",
            version: "v1.2.5.opt",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Shy_Guy_Lumber_Co.",
            youtubeUrl: null,
        },
        {
            file: "Z32",
            name: "Super Marine World",
            authors: "MrFluffy",
            version: "v1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Super_Marine_World",
            youtubeUrl: null,
        },
        {
            file: "Z33",
            name: "Icebound Stronghold",
            authors: "KaneTheSnowman",
            version: "v2.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Icebound_Stronghold",
            youtubeUrl: null,
        },
        {
            file: "Z34",
            name: "Kamek's Library",
            authors: "MysterE99",
            version: "v2.1.4",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Kamek%27s_Library_(MysterE99)",
            youtubeUrl: null,
        },
        {
            file: "Z35",
            name: "Wario Circuit",
            authors: "MysterE99",
            version: "v3.11.mkd",
            laps: 5.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Wario_Circuit_(MysterE99)",
            youtubeUrl: null,
        },
        {
            file: "Z36",
            name: "Sunrise Slopes",
            authors: "bugsy",
            version: "v1.0",
            laps: 1.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Sunrise_Slopes",
            youtubeUrl: null,
        },
        {
            file: "Z37",
            name: "Banished Courtyard",
            authors: "Metabus",
            version: "v1.0.opt",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Banished_Courtyard_(Banished_Keep_Texture)",
            youtubeUrl: null,
        },
        {
            file: "Z38",
            name: "Shadow Woods",
            authors: "Sniki",
            version: "v1.3",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Shadow_Woods",
            youtubeUrl: null,
        },
        {
            file: "Z39",
            name: "Hells Dimension",
            authors: "Jasperr",
            version: "v1.0-alt",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Red_Rooms",
            youtubeUrl: null,
        },
        {
            file: "Z40",
            name: "Botania",
            authors: "SpyKid",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Botania",
            youtubeUrl: null,
        },
        {
            file: "Z41",
            name: "Cascade Kingdom",
            authors: "SpyKid, ZPL",
            version: "v2.01",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Cascade_Kingdom",
            youtubeUrl: null,
        },
        {
            file: "Z42",
            name: "Sandcastle Park",
            authors: "SpyKid, ZPL",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Sandcastle_Park",
            youtubeUrl: null,
        },
        {
            file: "Z43",
            name: "Emerald Coast",
            authors: "Squadaloo",
            version: "v1.0.1.mkd",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Emerald_Coast",
            youtubeUrl: null,
        },
        {
            file: "Z44",
            name: "Super Bell Circuit",
            authors: "Squadaloo",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Super_Bell_Circuit",
            youtubeUrl: null,
        },
        {
            file: "Z45",
            name: "Midnight Museum",
            authors: "SquireTurnbolt",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Midnight_Museum",
            youtubeUrl: null,
        },
        {
            file: "Z46",
            name: "Crystal Canopy",
            authors: "ZPL",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Crystal_Canopy",
            youtubeUrl: null,
        },
        {
            file: "Z47",
            name: "Shy Guy Skies",
            authors: "SquireTurnbolt, Atmosphere",
            version: "v1.1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Shy_Guy_Skies",
            youtubeUrl: null,
        },
        {
            file: "Z48",
            name: "Forgotten Facility",
            authors: "Citrus",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Forgotten_Facility",
            youtubeUrl: null,
        },
        {
            file: "Z49",
            name: "Kitayama Keep",
            authors: "TacoJosh",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Kitayama_Keep",
            youtubeUrl: null,
        },
        {
            file: "Z50",
            name: "Dolphin Harbor",
            authors: "SpyKid",
            version: "v1.0.mkd",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Dolphin_Harbor",
            youtubeUrl: null,
        },
        {
            file: "Z51",
            name: "Aqua Dungeon",
            authors: "ZPL",
            version: "v2.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Aqua_Dungeon",
            youtubeUrl: null,
        },
        {
            file: "Z52",
            name: "Divine Paradise",
            authors: "ZPL",
            version: "v2.2.mkd",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Divine_Paradise",
            youtubeUrl: null,
        },
        {
            file: "Z53",
            name: "Moonlit Grounds",
            authors: "bugsy",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Moonlit_Grounds",
            youtubeUrl: null,
        },
        {
            file: "Z54",
            name: "Frigid Freezeway",
            authors: "ZPL",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Frigid_Freezeway",
            youtubeUrl: null,
        },
        {
            file: "Z55",
            name: "Honeyhive Falls",
            authors: "Fuffina, RustyCowboi333",
            version: "v1.2",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Honeyhive_Falls",
            youtubeUrl: null,
        },
        {
            file: "Z56",
            name: "Heavenly Sanctuary",
            authors: "ZPL",
            version: "v1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Heavenly_Sanctuary",
            youtubeUrl: null,
        },
        {
            file: "Z57",
            name: "Luigi's Island",
            authors: "ZPL",
            version: "v4.51",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Luigi%27s_Island_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "Z58",
            name: "Mystic Tangle",
            authors: "ZPL",
            version: "v1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Mystic_Tangle",
            youtubeUrl: null,
        },
        {
            file: "Z59",
            name: "Maplewood Caverns",
            authors: "ZPL",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Maplewood_Caverns",
            youtubeUrl: null,
        },
        {
            file: "Z60",
            name: "Fiery Factory, Fading Frost",
            authors: "Cotni",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Fiery_Factory,_Fading_Frost",
            youtubeUrl: null,
        },
        {
            file: "Z61",
            name: "Sunset Forest",
            authors: "ZPL",
            version: "v1.0.opt",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Sunset_Forest_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "Z62",
            name: "Pandora Palace",
            authors: "Shorky",
            version: "Beta-alt",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Pandora_Palace",
            youtubeUrl: null,
        },
        {
            file: "Z63",
            name: "Comet Starway",
            authors: "WiiLuigi, ZPL",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Comet_Starway",
            youtubeUrl: null,
        },
        {
            file: "Z64",
            name: "The Seamlands",
            authors: "Metabus, Fuffina, ._.",
            version: "v1.25",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/The_Seamlands",
            youtubeUrl: null,
        },
        {
            file: "Z65",
            name: "Northern Heights",
            authors: "Lovelifeandtpose024",
            version: "v2.3.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Northern_Heights",
            youtubeUrl: null,
        },
        {
            file: "Z66",
            name: "Thunder City",
            authors: "BigOto2, Fuffina",
            version: "v2.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Thunder_City_(The_World_That_Never_Was)",
            youtubeUrl: null,
        },
        {
            file: "Z67",
            name: "Goomba Circuit",
            authors: "UmbreonTurtle",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Goomba_Circuit",
            youtubeUrl: null,
        },
        {
            file: "Z68",
            name: "Propeller Paradise",
            authors: "Mickeyman713",
            version: "v1.2",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Propeller_Paradise",
            youtubeUrl: null,
        },
        {
            file: "Z69",
            name: "\u00b5Torrent's Divinity",
            authors: "Empex",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/%CE%9CTorrent%27s_Divinity",
            youtubeUrl: null,
        },
        {
            file: "Z70",
            name: "Ghostly Gulch",
            authors: "TacoJosh",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Ghostly_Gulch",
            youtubeUrl: null,
        },
        {
            file: "Z71",
            name: "Cubing Conundrum",
            authors: "adam",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Cubing_Conundrum",
            youtubeUrl: null,
        },
        {
            file: "Z72",
            name: "Daisy Gardens",
            authors: "xBlue98",
            version: "v2.2e",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Daisy_Gardens",
            youtubeUrl: null,
        },
        {
            file: "Z73",
            name: "Lunar Lights",
            authors: "Sniki",
            version: "v1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Lunar_Lights",
            youtubeUrl: null,
        },
        {
            file: "Z74",
            name: "Fruity Folly",
            authors: "Fuffina, liamonade07",
            version: "v1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Fruity_Folly",
            youtubeUrl: null,
        },
        {
            file: "Z75",
            name: "Thunder Canyon",
            authors: "bugsy",
            version: "v2.0",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Thunder_Canyon",
            youtubeUrl: null,
        },
        {
            file: "Z76",
            name: "Fungal Jungle",
            authors: "TacoJosh",
            version: "v1.21",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Fungal_Jungle",
            youtubeUrl: null,
        },
        {
            file: "Z77",
            name: "Cherry Blossom Garden",
            authors: "Renegade Ciara, ChaosShadow23",
            version: "v2.3",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Cherry_Blossom_Garden",
            youtubeUrl: null,
        },
        {
            file: "Z78",
            name: "Frostburn Fortress",
            authors: "Waltz, Vanillavaquita",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Frostburn_Fortress",
            youtubeUrl: null,
        },
        {
            file: "Z79",
            name: "Seaside Palace",
            authors: "Waltz, Rover",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Seaside_Palace",
            youtubeUrl: null,
        },
        {
            file: "Z80",
            name: "Vile Isle",
            authors: "Citrus",
            version: "v1.4.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Vile_Isle",
            youtubeUrl: null,
        },
        {
            file: "Z81",
            name: "Blooper Ruins",
            authors: "UmbreonTurtle",
            version: "v1.0",
            laps: 2.0,
            wikiUrl: "https://wiki.tockdom.com/wiki/Blooper_Ruins",
            youtubeUrl: null,
        },
        {
            file: "Z82",
            name: "Blizzerno Fortress",
            authors: "FunkyRacer",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Blizzerno_Fortress",
            youtubeUrl: null,
        },
        {
            file: "Z83",
            name: "Desert Fort",
            authors: "JorisMKW",
            version: "v3.0a",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Desert_Fort",
            youtubeUrl: null,
        },
        {
            file: "Z84",
            name: "Spectral Station",
            authors: "MrFluffy",
            version: "v1.1",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Spectral_Station",
            youtubeUrl: null,
        },
        {
            file: "Z85",
            name: "Bouldergeist's Ghostly Manor",
            authors: "Bits",
            version: "v1.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Bouldergeist%27s_Ghostly_Manor",
            youtubeUrl: null,
        },
        {
            file: "Z86",
            name: "Forest Creek",
            authors: "Bits",
            version: "v3.0",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Forest_Creek_(Bits)",
            youtubeUrl: null,
        },
        {
            file: "Z87",
            name: "Mushlight's Reprise",
            authors: "Fuffina",
            version: "Beta",
            laps: "-",
            wikiUrl: "https://wiki.tockdom.com/wiki/Mushlight%27s_Reprise",
            youtubeUrl: null,
        }
    ],
    battle: [
        {
            file: "old_battle4_sfc",
            name: "SNES Battle Course 4",
            authors: "Nintendo",
            version: "-",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "sfcMC1",
            name: "SNES Mario Circuit 1",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Mario_Circuit_1_(Battle_Arena)_(SNES_Mario_Circuit_1_Edit)",
            youtubeUrl: null,
        },
        {
            file: "sfcVL2",
            name: "SNES Vanilla Lake 2",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/SNES_Vanilla_Lake_2_(Battle_Arena)_(SNES_Vanilla_Lake_2_Edit)",
            youtubeUrl: null,
        },
        {
            file: "n64BD",
            name: "N64 Big Donut",
            authors: "UltraWario",
            version: "v1.2",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/N64_Big_Donut_(UltraWario)",
            youtubeUrl: null,
        },
        {
            file: "n64BF",
            name: "N64 Block Fort",
            authors: "AltairYoshi",
            version: "v1.2",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/N64_Block_Fort_(AltairYoshi)",
            youtubeUrl: null,
        },
        {
            file: "old_matenro_64",
            name: "N64 Skyscraper",
            authors: "Nintendo",
            version: "-",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "n64BB",
            name: "N64 Banshee Boardwalk",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/N64_Banshee_Boardwalk_(Battle_Arena)_(N64_Banshee_Boardwalk_Edit)",
            youtubeUrl: null,
        },
        {
            file: "gBC1",
            name: "GBA Battle Course 1",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Battle_Course_1_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "gBC2",
            name: "GBA Battle Course 2",
            authors: "ZPL",
            version: "v1.1",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Battle_Course_2_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "old_battle3_gba",
            name: "GBA Battle Course 3",
            authors: "Nintendo",
            version: "-",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "gBC4",
            name: "GBA Battle Course 4",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GBA_Battle_Course_4_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "old_cookieland_gc",
            name: "GCN Cookie Land",
            authors: "Nintendo",
            version: "-",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "gcnBC",
            name: "GCN Block City",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Block_City_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "gcnGC",
            name: "GCN Nintendo Gamecube",
            authors: "Tock",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Nintendo_GameCube_(Tock)",
            youtubeUrl: null,
        },
        {
            file: "gcnPP",
            name: "GCN Pipe Plaza",
            authors: "ZPL",
            version: "v1.1",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Pipe_Plaza_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "gcnBP",
            name: "GCN Baby Park",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Baby_Park_(Battle_Arena)_(GCN_Baby_Park_Edit)",
            youtubeUrl: null,
        },
        {
            file: "gcnBoC",
            name: "GCN Bowser's Castle",
            authors: "ZPL",
            version: "v1.1",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/GCN_Bowser%27s_Castle_(Battle_Arena)_(GCN_Bowser%27s_Castle_Edit)",
            youtubeUrl: null,
        },
        {
            file: "dsbDS",
            name: "DS Nintendo DS",
            authors: "AltairYoshi",
            version: "v1.5",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_Nintendo_DS_(AltairYoshi)",
            youtubeUrl: null,
        },
        {
            file: "old_house_ds",
            name: "DS Twilight House",
            authors: "Nintendo",
            version: "-",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "dsPS",
            name: "DS Palm Shore",
            authors: "Retrostyle12",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_Palm_Shore_(Retrostyle12)",
            youtubeUrl: null,
        },
        {
            file: "dsTT",
            name: "DS Tart Top",
            authors: "Questorian",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_Tart_Top_(Questorian)",
            youtubeUrl: null,
        },
        {
            file: "dsWS",
            name: "DS Water Stage",
            authors: "UltraWario",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_MR_stage1_(UltraWario)",
            youtubeUrl: null,
        },
        {
            file: "dsLA",
            name: "DS Lava Arena",
            authors: "UltraWario",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_MR_stage3_(UltraWario)",
            youtubeUrl: null,
        },
        {
            file: "dsTTC",
            name: "DS Tick-Tock Clock",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_Tick-Tock_Clock_(Battle_Arena)_(DS_Tick-Tock_Clock_Edit)",
            youtubeUrl: null,
        },
        {
            file: "block_battle",
            name: "Wii Block Plaza",
            authors: "Nintendo",
            version: "v1.0",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "venice_battle",
            name: "Wii Delfino Pier",
            authors: "Nintendo",
            version: "v1.0",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "skate_battle",
            name: "Wii Funky Stadium",
            authors: "Nintendo",
            version: "v1.0",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "casino_battle",
            name: "Wii Chain Chomp Wheel",
            authors: "Nintendo",
            version: "v1.0",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "sand_battle",
            name: "Wii Thwomp Desert",
            authors: "Nintendo",
            version: "v1.0",
            laps: null,
            youtubeUrl: null,
        },
        {
            file: "wGC",
            name: "Wii Galaxy Colosseum",
            authors: "Nintendo, Zeraora, Ro",
            version: "v1.0-br",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/Galaxy_Colosseum_(Battle_Arena)_(Galaxy_Colosseum_Edit)_(Zeraora_%26_Ro)",
            youtubeUrl: null,
        },
        {
            file: "wMMM",
            name: "Wii Moo Moo Meadows",
            authors: "ZPL, TheBeefBai",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/Wii_Moo_Moo_Meadows_(Battle_Arena)_(Moo_Moo_Meadows_Edit)_(ZPL_%26_TheBeefBai)",
            youtubeUrl: null,
        },
        {
            file: "wCM",
            name: "Wii Coconut Mall",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/Coconut_Mall_(Battle_Arena)_(Coconut_Mall_Edit)_(ZPL)",
            youtubeUrl: null,
        },
        {
            file: "wRR",
            name: "Wii Rainbow Road",
            authors: "ZPL, TheBeefBai",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/Rainbow_Road_(Battle_Arena)_(Rainbow_Road_Edit)",
            youtubeUrl: null,
        },
        {
            file: "3dsHH",
            name: "3DS Honeybee Hive",
            authors: "Atlas",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Honeybee_Hive_(Atlas)",
            youtubeUrl: null,
        },
        {
            file: "3dsSR",
            name: "3DS Sherbet Rink",
            authors: "Diego Vapy",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Sherbet_Rink_(Diego_Vapy)",
            youtubeUrl: null,
        },
        {
            file: "3dsDH",
            name: "3DS Daisy Hills",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/3DS_Daisy_Hills_(Battle_Arena)_(3DS_Daisy_Hills_Edit)",
            youtubeUrl: null,
        },
        {
            file: "uACB",
            name: "Wii U Animal Crossing",
            authors: "ZPL, TheBeefBai",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/Wii_U_Animal_Crossing_(Battle_Arena)_(Wii_U_Animal_Crossing_Edit)",
            youtubeUrl: null,
        },
        {
            file: "sBS",
            name: "SW Battle Stadium",
            authors: "SamanthaMK",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/SW_Battle_Stadium_(SamanthaMK)",
            youtubeUrl: null,
        },
        {
            file: "tPPB",
            name: "Tour Paris Promenade B",
            authors: "SamanthaMK",
            version: "v1.1.1",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/Tour_Paris_Promenade_B_(SamanthaMK)",
            youtubeUrl: null,
        },
        {
            file: "dsNBB",
            name: "Beta Nokonoko Beach",
            authors: "ZPL",
            version: "v1.0",
            laps: null,
            wikiUrl: "https://wiki.tockdom.com/wiki/DS_Nokonoko_Beach_(Battle_Arena)_(DS_Nokonoko_Beach_Edit)",
            youtubeUrl: null,
        }
    ],
};

export const consoleDisplayNames: Record<string, string> = {
    "SNES": "Super Nintendo (SNES)",
    "N64": "Nintendo 64",
    "GBA": "Game Boy Advance",
    "GCN": "GameCube",
    "DS": "Nintendo DS",
    "SW": "Switch",
    "Wii": "Wii",
    "3DS": "Nintendo 3DS",
    "Wii U": "Wii U",
    "Tour": "Mario Kart Tour",
    "RMX": "RMX Tracks",
    "GP": "Arcade GP Series",
    "SW2": "Switch 2",
    "Beta": "Beta Tracks"
};